// players-data.ts
// Shared player pool for Career Path Guesser and Stat Shadow
// 80+ players — enough for 2+ years of daily games with no repeats

export interface PlayerEntry {
  name: string;
  career: string[];       // ordered team abbreviations (can repeat for each year played)
  positions: string[];
  draftYear?: number;
  college?: string;
  notableFact?: string;
  clues: string[];        // 5 clues per player (hardest used first, easiest last)
}

// Returns deduplicated career journey: ["NE","NE","TB"] → ["NE","TB"]
export function careerJourney(player: PlayerEntry): string[] {
  return player.career.filter((team, i, arr) => i === 0 || team !== arr[i - 1]);
}

// Seed-based daily index — same player every day, cycles through the list
export function getDailyPlayerIndex(poolSize: number, offset = 0): number {
  const today = new Date().toISOString().split('T')[0];
  const seed = today.split('-').reduce((acc, val) => acc + parseInt(val), 0) + offset;
  return seed % poolSize;
}

export const NFL_PLAYERS: PlayerEntry[] = [
  {
    name: "Tom Brady",
    career: ["NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","TB","TB","TB"],
    positions: ["QB"], draftYear: 2000, college: "Michigan",
    notableFact: "7x Super Bowl Champion — the most of any player in NFL history.",
    clues: [
      "His jersey was stolen twice after two different Super Bowl victories",
      "Was selected 199th overall in the 6th round of the 2000 NFL Draft",
      "Played 20 seasons in New England before leaving in free agency",
      "Won a Super Bowl in his first season with Tampa Bay",
      "Holds the all-time records for career passing yards and touchdown passes",
    ],
  },
  {
    name: "Patrick Mahomes",
    career: ["KC","KC","KC","KC","KC","KC","KC","KC"],
    positions: ["QB"], draftYear: 2017, college: "Texas Tech",
    notableFact: "3x Super Bowl champion — considered by many the best QB of his generation.",
    clues: [
      "Was also drafted by the Detroit Tigers as a baseball pitcher out of high school",
      "Son of former MLB pitcher Pat Mahomes Sr.",
      "Famous for his no-look passes and sidearm throws under pressure",
      "Threw for 5,097 yards and 50 TDs in his first full season as a starter",
      "Has won multiple Super Bowls with the Kansas City Chiefs",
    ],
  },
  {
    name: "Jerry Rice",
    career: ["SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","OAK","OAK","OAK","SEA"],
    positions: ["WR"], draftYear: 1985, college: "Mississippi Valley State",
    notableFact: "Widely regarded as the greatest wide receiver — and player — in NFL history.",
    clues: [
      "Famously trained by running steep hills in the California hills each offseason",
      "Drafted 16th overall in 1985 out of a small Division I-AA program",
      "Was a 13x Pro Bowler throughout his career",
      "Won 3 Super Bowls with the San Francisco 49ers",
      "Holds all-time records for receiving yards, TDs, and receptions",
    ],
  },
  {
    name: "Lawrence Taylor",
    career: ["NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG"],
    positions: ["LB"], draftYear: 1981, college: "North Carolina",
    notableFact: "Changed how the NFL values edge rushers — 2x Super Bowl champion, 1986 MVP.",
    clues: [
      "Nicknamed 'LT'",
      "Was drafted 2nd overall in 1981 out of North Carolina",
      "Recorded 132.5 career sacks playing outside linebacker",
      "Won the NFL MVP award in 1986 — rare for a defensive player",
      "Won 2 Super Bowls with the New York Giants",
    ],
  },
  {
    name: "Peyton Manning",
    career: ["IND","IND","IND","IND","IND","IND","IND","IND","IND","IND","IND","IND","IND","IND","DEN","DEN","DEN","DEN"],
    positions: ["QB"], draftYear: 1998, college: "Tennessee",
    notableFact: "2x Super Bowl champion, 5x MVP — one of the most cerebral QBs ever.",
    clues: [
      "Was selected #1 overall in the 1998 NFL Draft out of Tennessee",
      "Son of NFL QB Archie Manning and older brother of Eli Manning",
      "Famous for his pre-snap audibles and reading defenses at the line",
      "Holds the record for most NFL MVP awards with 5",
      "Won a Super Bowl with both the Colts and the Broncos",
    ],
  },
  {
    name: "Barry Sanders",
    career: ["DET","DET","DET","DET","DET","DET","DET","DET","DET","DET"],
    positions: ["RB"], draftYear: 1989, college: "Oklahoma State",
    notableFact: "Retired just 1,458 yards short of the all-time record — many consider him the greatest rusher ever.",
    clues: [
      "Known for his elusiveness — rarely made first contact at the line of scrimmage",
      "Shocked the NFL world by abruptly retiring before the 1999 season",
      "Won the Heisman Trophy in 1988 at Oklahoma State",
      "Rushed for over 1,000 yards in each of his 10 NFL seasons",
      "Played his entire career with the Detroit Lions",
    ],
  },
  {
    name: "Reggie White",
    career: ["PHI","PHI","PHI","PHI","PHI","PHI","PHI","PHI","GB","GB","GB","GB","GB","GB","CAR","CAR"],
    positions: ["DE"], draftYear: 1984, college: "Tennessee",
    notableFact: "The 'Minister of Defense' — 198 career sacks, 2x NFL Defensive Player of the Year.",
    clues: [
      "Selected in the 1984 supplemental draft after playing in the USFL",
      "His signature move was called the 'hump move' — a violent bull rush into a rip",
      "Recorded 198 career sacks — a record when he retired",
      "Won Super Bowl XXXI with the Green Bay Packers",
      "Nicknamed the 'Minister of Defense' due to his ordained ministry",
    ],
  },
  {
    name: "Deion Sanders",
    career: ["ATL","ATL","ATL","ATL","ATL","ATL","SF","DAL","DAL","DAL","WAS","BAL"],
    positions: ["CB","KR"], draftYear: 1989, college: "Florida State",
    notableFact: "The only person to play in both a Super Bowl and a World Series — 'Prime Time'.",
    clues: [
      "Later became head coach at Jackson State and then Colorado",
      "Also played MLB for the Braves, Yankees, Reds, and Giants",
      "Known for elite man coverage and return ability",
      "Won 2 Super Bowls — first with San Francisco, then with Dallas",
      "Nicknamed 'Prime Time' and 'Neon Deion'",
    ],
  },
  {
    name: "Randy Moss",
    career: ["MIN","MIN","MIN","MIN","MIN","MIN","MIN","OAK","OAK","NE","NE","MIN","TEN","SF","SF"],
    positions: ["WR"], draftYear: 1998, college: "Marshall",
    notableFact: "Set the single-season TD reception record with 23 in 2007.",
    clues: [
      "Slipped to the 21st pick in 1998 due to off-field concerns coming out of Marshall",
      "Known for his deep threat — virtually unguardable on go routes",
      "Was considered a 'problem player' early in his career despite elite production",
      "Played for 6 different NFL teams over his career",
      "Set the NFL record for receiving TDs in a single season with 23 in 2007",
    ],
  },
  {
    name: "Emmitt Smith",
    career: ["DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","ARI","ARI","DAL"],
    positions: ["RB"], draftYear: 1990, college: "Florida",
    notableFact: "The NFL's all-time leading rusher with 18,355 career yards.",
    clues: [
      "Was selected 17th overall in 1990 out of Florida",
      "Played the bulk of his career in Dallas before a stint in Arizona",
      "Named MVP of Super Bowl XXVIII",
      "Won 3 Super Bowls with the Dallas Cowboys",
      "The NFL's all-time leading rusher in career yards",
    ],
  },
  {
    name: "Joe Montana",
    career: ["SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","KC","KC"],
    positions: ["QB"], draftYear: 1979, college: "Notre Dame",
    notableFact: "4x Super Bowl champion — never threw a postseason interception in 4 Super Bowl starts.",
    clues: [
      "Was drafted in the 3rd round of the 1979 NFL Draft out of Notre Dame",
      "Nicknamed 'Joe Cool' for his composure in pressure situations",
      "Finished his career with the Kansas City Chiefs",
      "Named Super Bowl MVP 3 times",
      "Won 4 Super Bowls — all with the San Francisco 49ers",
    ],
  },
  {
    name: "Walter Payton",
    career: ["CHI","CHI","CHI","CHI","CHI","CHI","CHI","CHI","CHI","CHI","CHI","CHI","CHI"],
    positions: ["RB"], draftYear: 1975, college: "Jackson State",
    notableFact: "'Sweetness' — 9-time Pro Bowler and 1985 Super Bowl champion.",
    clues: [
      "Drafted 4th overall in 1975 out of Jackson State — a historically Black university",
      "Known as much for his blocking ability as his rushing production",
      "Held the all-time rushing record before Emmitt Smith broke it",
      "Won Super Bowl XX with the Chicago Bears",
      "Nicknamed 'Sweetness'",
    ],
  },
  {
    name: "John Elway",
    career: ["DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN"],
    positions: ["QB"], draftYear: 1983, college: "Stanford",
    notableFact: "Won back-to-back Super Bowls to close his career — MVP of Super Bowl XXXIII.",
    clues: [
      "Forced a trade from the Baltimore Colts to Denver after being selected #1 overall in 1983",
      "Was also a legitimate baseball prospect, drafted by the New York Yankees",
      "Famous for 'The Drive' — a 98-yard game-tying drive in the 1986 AFC Championship",
      "Named MVP of Super Bowl XXXIII in his final game",
      "Won 2 Super Bowls at the end of his career with the Denver Broncos",
    ],
  },
  {
    name: "Brett Favre",
    career: ["ATL","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","NYJ","MIN","MIN"],
    positions: ["QB"], draftYear: 1991, college: "Southern Miss",
    notableFact: "Held the record for consecutive starts by a QB at 297 — 3x consecutive MVP.",
    clues: [
      "Grew up in Kiln, Mississippi and attended Southern Miss",
      "Came out of retirement twice — once for the Jets, then the Vikings",
      "Won 3 consecutive NFL MVP awards from 1995 to 1997",
      "Won Super Bowl XXXI with the Green Bay Packers",
      "Played 297 consecutive regular-season games — the most by any QB in history",
    ],
  },
  {
    name: "Dan Marino",
    career: ["MIA","MIA","MIA","MIA","MIA","MIA","MIA","MIA","MIA","MIA","MIA","MIA","MIA","MIA","MIA","MIA","MIA"],
    positions: ["QB"], draftYear: 1983, college: "Pittsburgh",
    notableFact: "Never won a Super Bowl despite setting countless passing records.",
    clues: [
      "Was passed over by 26 teams before Miami selected him in the 1983 draft",
      "Reached the Super Bowl in only his second season and never returned",
      "Famous for his lightning-quick release — considered among the best ever",
      "Set the then-record for single-season TD passes with 48 in 1984",
      "Played his entire 17-season career with the Miami Dolphins",
    ],
  },
  {
    name: "Aaron Rodgers",
    career: ["GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","GB","NYJ","NYJ"],
    positions: ["QB"], draftYear: 2005, college: "Cal",
    notableFact: "Super Bowl XLV champion, 4x MVP — one of the most efficient QBs in history.",
    clues: [
      "Was selected 24th overall in 2005 — famously sat on camera watching the entire first round pass him by",
      "Tore his Achilles tendon just 4 snaps into his Jets debut",
      "Traded to the New York Jets in 2023 after 18 seasons in Green Bay",
      "Has won 4 NFL MVP awards",
      "Won Super Bowl XLV with the Green Bay Packers and was named MVP",
    ],
  },
  {
    name: "Calvin Johnson",
    career: ["DET","DET","DET","DET","DET","DET","DET","DET","DET"],
    positions: ["WR"], draftYear: 2007, college: "Georgia Tech",
    notableFact: "'Megatron' — set the single-season receiving yards record with 1,964 in 2012.",
    clues: [
      "Drafted 2nd overall in 2007 out of Georgia Tech",
      "Was a 6x Pro Bowler and 3x All-Pro selection",
      "Played his entire career with the Detroit Lions — who never reached the playoffs during his tenure",
      "Set the single-season receiving yards record with 1,964 yards in 2012",
      "Nicknamed 'Megatron' for his combination of size, speed, and leaping ability",
    ],
  },
  {
    name: "Adrian Peterson",
    career: ["MIN","MIN","MIN","MIN","MIN","MIN","MIN","MIN","MIN","MIN","NO","ARI","WAS","WAS","DET","TEN","SEA","TEN"],
    positions: ["RB"], draftYear: 2007, college: "Oklahoma",
    notableFact: "Rushed for 2,097 yards in 2012 — just 9 yards short of the all-time single-season record.",
    clues: [
      "Was selected 7th overall in 2007 out of Oklahoma",
      "Played for 7 different teams during his career",
      "Known as 'AD' — All Day",
      "Came back from a torn ACL/MCL to win NFL MVP the following season",
      "Rushed for 2,097 yards in a single season — the second-most in NFL history",
    ],
  },
  {
    name: "Ray Lewis",
    career: ["BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL"],
    positions: ["LB"], draftYear: 1996, college: "Miami (FL)",
    notableFact: "2x Super Bowl champion, 13x Pro Bowler — the defining linebacker of his era.",
    clues: [
      "Played all 17 of his NFL seasons with the Baltimore Ravens",
      "Famous for his pregame squats and entrance dance ritual",
      "Won the Defensive Player of the Year award twice",
      "Named Super Bowl XXXV MVP",
      "Won 2 Super Bowls with the Baltimore Ravens",
    ],
  },
  {
    name: "Ed Reed",
    career: ["BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","BAL","HOU","NYJ"],
    positions: ["S"], draftYear: 2002, college: "Miami (FL)",
    notableFact: "The all-time interception return yards leader — widely regarded as the best safety ever.",
    clues: [
      "Drafted 24th overall in 2002 out of the University of Miami",
      "Known for his football IQ — often predicted routes before the snap",
      "Played alongside Ray Lewis for most of his career",
      "Won Super Bowl XLVII with the Baltimore Ravens",
      "Holds the NFL record for career interception return yards",
    ],
  },
  {
    name: "Terrell Owens",
    career: ["SF","SF","SF","SF","SF","SF","SF","SF","PHI","DAL","DAL","DAL","BUF","CIN","SEA"],
    positions: ["WR"], draftYear: 1996, college: "Tennessee-Chattanooga",
    notableFact: "3rd all-time in receiving yards and TDs — one of the most polarizing players ever.",
    clues: [
      "Was drafted in the 3rd round in 1996 out of Tennessee-Chattanooga",
      "Played for 6 different NFL teams throughout his career",
      "Famously did sit-ups in his driveway during a contract holdout in Dallas",
      "Finished his career 3rd all-time in receiving yards and touchdown receptions",
      "Known as 'T.O.' — one of the most flamboyant personalities in NFL history",
    ],
  },
  {
    name: "LaDainian Tomlinson",
    career: ["SD","SD","SD","SD","SD","SD","SD","SD","SD","NYJ","NYJ"],
    positions: ["RB"], draftYear: 2001, college: "TCU",
    notableFact: "Set the single-season TD record with 28 in 2006 — also threw 2 TDs that year.",
    clues: [
      "Was selected 5th overall in 2001 out of TCU",
      "Known for his quickness, vision, and receiving ability out of the backfield",
      "Played 9 seasons with the San Diego Chargers before finishing with the Jets",
      "Won the NFL MVP award in 2006",
      "Set the NFL record for touchdowns in a single season with 28 in 2006",
    ],
  },
  {
    name: "Marshawn Lynch",
    career: ["BUF","BUF","BUF","BUF","SEA","SEA","SEA","SEA","SEA","SEA","SEA","SEA","OAK","SEA"],
    positions: ["RB"], draftYear: 2007, college: "Cal",
    notableFact: "'Beast Mode' — his 2011 playoff run against the Saints is one of the greatest runs in NFL history.",
    clues: [
      "Was traded from Buffalo to Seattle midseason in 2010",
      "Was famously silent with media — fined for refusing to speak to reporters",
      "Won Super Bowl XLVIII with the Seattle Seahawks",
      "Famous for his 'Beast Quake' run in the 2010 NFC Wild Card game",
      "Nicknamed 'Beast Mode'",
    ],
  },
  {
    name: "Jim Brown",
    career: ["CLE","CLE","CLE","CLE","CLE","CLE","CLE","CLE","CLE"],
    positions: ["RB"], draftYear: 1957, college: "Syracuse",
    notableFact: "Retired at his peak — still considered by many to be the greatest football player of all time.",
    clues: [
      "Also a lacrosse All-American at Syracuse University",
      "Abruptly retired at age 29 to pursue an acting career",
      "Averaged 5.2 yards per carry over his entire NFL career",
      "Led the Cleveland Browns to an NFL Championship in 1964",
      "Played 9 seasons and led his team in rushing in every single one",
    ],
  },
  {
    name: "Troy Aikman",
    career: ["DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL"],
    positions: ["QB"], draftYear: 1989, college: "UCLA",
    notableFact: "3x Super Bowl champion with the Dallas Cowboys dynasty.",
    clues: [
      "Later became a long-time NFL play-by-play broadcaster for Fox Sports",
      "Named Super Bowl XXVII MVP",
      "Part of the 'Triplets' alongside Michael Irvin and Emmitt Smith",
      "Was selected #1 overall in the 1989 NFL Draft",
      "Won 3 Super Bowls with the Dallas Cowboys in a 4-year span",
    ],
  },
  {
    name: "Michael Irvin",
    career: ["DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL"],
    positions: ["WR"], draftYear: 1988, college: "Miami (FL)",
    notableFact: "'The Playmaker' — 3x Super Bowl champion and Hall of Famer.",
    clues: [
      "Part of the famous 'Triplets' with Troy Aikman and Emmitt Smith",
      "Was selected 11th overall in 1988 out of the University of Miami",
      "Had 5 consecutive 1,000+ yard receiving seasons",
      "Won 3 Super Bowls as part of the Dallas Cowboys dynasty",
      "Nicknamed 'The Playmaker'",
    ],
  },
  {
    name: "Steve Young",
    career: ["TB","TB","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF","SF"],
    positions: ["QB"], draftYear: 1984, college: "BYU",
    notableFact: "Named Super Bowl XXIX MVP after throwing a record 6 TD passes — 2x NFL MVP.",
    clues: [
      "Is a direct descendant of Brigham Young, the founder of the LDS Church",
      "Won 2 NFL MVP awards",
      "Started his NFL career with 2 rough seasons with the Tampa Bay Buccaneers",
      "Held the career passer rating record when he retired",
      "Named Super Bowl XXIX MVP after throwing a record 6 touchdown passes",
    ],
  },
  {
    name: "Tony Gonzalez",
    career: ["KC","KC","KC","KC","KC","KC","KC","KC","KC","KC","KC","KC","ATL","ATL","ATL","ATL","ATL"],
    positions: ["TE"], draftYear: 1997, college: "Cal",
    notableFact: "Redefined the tight end position — 14x Pro Bowler and all-time TE receiving leader.",
    clues: [
      "Was selected 13th overall in the 1997 NFL Draft",
      "Also played college basketball at Cal and was considered an NBA prospect",
      "Spent the first 12 seasons of his career with the Kansas City Chiefs",
      "Holds the records for most receptions, yards, and TDs by a tight end",
      "Revolutionized the tight end position — a 14x Pro Bowler",
    ],
  },
  {
    name: "Rob Gronkowski",
    career: ["NE","NE","NE","NE","NE","NE","NE","NE","NE","NE","TB","TB"],
    positions: ["TE"], draftYear: 2010, college: "Arizona",
    notableFact: "4x Super Bowl champion — widely considered the greatest TE in NFL history.",
    clues: [
      "Was selected 42nd overall in 2010 after missing an entire college season with a back injury",
      "Considered the most dominant blocking tight end in NFL history",
      "Retired once before coming back to play alongside Tom Brady in Tampa",
      "Nicknamed 'Gronk' — famous for his spiking celebrations after touchdowns",
      "Won 4 Super Bowls — 3 with New England and 1 with Tampa Bay",
    ],
  },
  {
    name: "Travis Kelce",
    career: ["KC","KC","KC","KC","KC","KC","KC","KC","KC","KC","KC","KC"],
    positions: ["TE"], draftYear: 2013, college: "Cincinnati",
    notableFact: "4x Super Bowl champion — the most decorated tight end in NFL history.",
    clues: [
      "Was selected 63rd overall in the 2013 NFL Draft out of Cincinnati",
      "Brother of former NFL center Jason Kelce",
      "Briefly appeared on a reality dating show called 'Catching Kelce' in 2016",
      "Holds the record for most consecutive 1,000-yard seasons by a tight end",
      "Has won multiple Super Bowls with the Kansas City Chiefs",
    ],
  },
  {
    name: "Odell Beckham Jr",
    career: ["NYG","NYG","NYG","NYG","NYG","CLE","CLE","LAR","BAL","MIA"],
    positions: ["WR"], draftYear: 2014, college: "LSU",
    notableFact: "His one-handed catch in 2014 is considered the greatest catch in NFL history.",
    clues: [
      "Was selected 12th overall in 2014 out of LSU",
      "Played for 5 different teams across his career",
      "Won Super Bowl LVI with the Los Angeles Rams before tearing his ACL in the game",
      "Made what many consider the greatest catch in NFL history — a one-handed grab against the Cowboys in 2014",
      "Known as 'OBJ'",
    ],
  },
  {
    name: "DeAndre Hopkins",
    career: ["HOU","HOU","HOU","HOU","HOU","HOU","HOU","ARI","ARI","ARI","TEN","KC"],
    positions: ["WR"], draftYear: 2013, college: "Clemson",
    notableFact: "5x Pro Bowler — famous for his one-handed catches and the 'Hail Murray'.",
    clues: [
      "Was selected 27th overall in 2013 out of Clemson",
      "Won the Biletnikoff Award as the nation's best college receiver in 2012",
      "Was controversially traded from Houston to Arizona for a second-round pick",
      "Made the 'Hail Murray' catch — a one-handed grab to win a game against Buffalo as time expired",
      "Nicknamed 'Nuk'",
    ],
  },
  {
    name: "Davante Adams",
    career: ["GB","GB","GB","GB","GB","GB","GB","GB","LV","LV","LV","NYJ"],
    positions: ["WR"], draftYear: 2014, college: "Fresno State",
    notableFact: "Led the NFL in touchdowns in both 2020 and 2021 — top-3 WR of his era.",
    clues: [
      "Was selected 53rd overall in 2014 out of Fresno State",
      "Requested a trade to Las Vegas to reunite with his college QB Derek Carr",
      "Was Aaron Rodgers' primary target for 8 seasons in Green Bay",
      "Led the NFL in touchdown receptions in consecutive seasons (2020 and 2021)",
      "One of the most precise route-runners in recent NFL history",
    ],
  },
  {
    name: "Tyreek Hill",
    career: ["KC","KC","KC","KC","KC","KC","MIA","MIA","MIA","MIA"],
    positions: ["WR"], draftYear: 2016, college: "West Alabama",
    notableFact: "The fastest player in the NFL — set the single-season receiving yards record in 2023.",
    clues: [
      "Also competed in USATF 100m open national championships as a sprinter",
      "Was first signed as an undrafted free agent by the Chiefs before being officially drafted in 2016",
      "Won Super Bowl LIV with the Kansas City Chiefs",
      "Set the single-season receiving yards record with 1,799 yards in 2023",
      "Nicknamed 'Cheetah' — ran a 4.29 40-yard dash at the NFL Combine",
    ],
  },
  {
    name: "Stefon Diggs",
    career: ["MIN","MIN","MIN","MIN","MIN","MIN","BUF","BUF","BUF","BUF","BUF","HOU"],
    positions: ["WR"], draftYear: 2015, college: "Maryland",
    notableFact: "Caught the 'Minneapolis Miracle' — a 61-yard walk-off TD in the 2018 playoffs.",
    clues: [
      "Was selected 146th overall in 2015 out of Maryland",
      "Younger brother of NFL cornerback Trevon Diggs",
      "Was traded from Minnesota to Buffalo in 2020",
      "Led the NFL in receptions and receiving yards in 2020 with the Bills",
      "Caught the 'Minneapolis Miracle' — a 61-yard walk-off TD to end the 2018 NFC Divisional playoff",
    ],
  },
  {
    name: "Justin Jefferson",
    career: ["MIN","MIN","MIN","MIN","MIN"],
    positions: ["WR"], draftYear: 2020, college: "LSU",
    notableFact: "Set the record for most receiving yards in a player's first four seasons in NFL history.",
    clues: [
      "Signed one of the richest WR contracts in NFL history in 2023",
      "Was drafted 22nd overall by Minnesota after Stefon Diggs was traded away",
      "Won a national championship at LSU in 2019 alongside Joe Burrow",
      "Known for his 'Griddy' touchdown celebration dance",
      "Set the NFL record for receiving yards in the first 4 seasons of a career",
    ],
  },
  {
    name: "Christian McCaffrey",
    career: ["CAR","CAR","CAR","CAR","CAR","CAR","SF","SF","SF"],
    positions: ["RB"], draftYear: 2017, college: "Stanford",
    notableFact: "Won the 2023 OPOY — one of the most versatile offensive players in NFL history.",
    clues: [
      "Was selected 8th overall in 2017 out of Stanford",
      "Son of former NFL wide receiver Ed McCaffrey",
      "Was traded from Carolina to San Francisco midseason in 2022",
      "Led the NFL in yards from scrimmage in 2023 and won the Offensive Player of the Year",
      "One of the most versatile offensive players in recent memory — can rush, catch, and throw",
    ],
  },
  {
    name: "Derrick Henry",
    career: ["TEN","TEN","TEN","TEN","TEN","TEN","TEN","TEN","TEN","BAL"],
    positions: ["RB"], draftYear: 2016, college: "Alabama",
    notableFact: "4x rushing champion — his 2020 season of 2,027 yards is one of the greatest ever.",
    clues: [
      "Was selected 45th overall in 2016 out of Alabama",
      "Had a legendary postseason performance against the Ravens where he rushed for 195 yards",
      "Nicknamed 'King Henry' — known for his power running and straight-line dominance",
      "Won 4 NFL rushing titles — including a 2,000+ yard season in 2020",
      "Won the Heisman Trophy in 2015 at Alabama",
    ],
  },
  {
    name: "Saquon Barkley",
    career: ["NYG","NYG","NYG","NYG","NYG","NYG","PHI","PHI"],
    positions: ["RB"], draftYear: 2018, college: "Penn State",
    notableFact: "Set the NFL single-season rushing record with 2,005 yards in 2024 with the Eagles.",
    clues: [
      "Was selected 2nd overall in 2018 out of Penn State",
      "Left the New York Giants as a free agent and signed with the rival Eagles",
      "Won Super Bowl LIX with the Philadelphia Eagles",
      "Won the Offensive Rookie of the Year award in 2018",
      "Set the NFL single-season rushing record with 2,005 yards in 2024",
    ],
  },
  {
    name: "Josh Allen",
    career: ["BUF","BUF","BUF","BUF","BUF","BUF","BUF"],
    positions: ["QB"], draftYear: 2018, college: "Wyoming",
    notableFact: "One of the most dangerous dual-threat QBs in NFL history.",
    clues: [
      "Was selected 7th overall in 2018 out of Wyoming",
      "Grew up in Firebaugh, California — a small agricultural community",
      "Known for his ability to scramble and run through would-be tacklers",
      "Has led the Buffalo Bills as their franchise QB since 2018",
      "One of the most physically imposing quarterbacks in recent NFL history",
    ],
  },
  {
    name: "Lamar Jackson",
    career: ["BAL","BAL","BAL","BAL","BAL","BAL","BAL"],
    positions: ["QB"], draftYear: 2018, college: "Louisville",
    notableFact: "Unanimous MVP in 2019 — first QB to win MVP unanimously since 1999.",
    clues: [
      "Was selected 32nd overall in 2018 — the final pick of the first round — out of Louisville",
      "Led the Baltimore Ravens to multiple AFC Championship Games",
      "Won a second MVP award in 2023",
      "Holds the single-season QB rushing yards record",
      "Won the NFL MVP award unanimously in 2019 — first QB to do so in 20 years",
    ],
  },
  {
    name: "Joe Burrow",
    career: ["CIN","CIN","CIN","CIN","CIN"],
    positions: ["QB"], draftYear: 2020, college: "LSU",
    notableFact: "Won the Heisman and a national title before leading Cincinnati to Super Bowl LVI.",
    clues: [
      "Was selected #1 overall in 2020",
      "Tore his ACL in his rookie season before returning to make a Super Bowl run",
      "Known for his laid-back personality and cigar celebration after winning the AFC Championship",
      "Led the Cincinnati Bengals to Super Bowl LVI in just his second NFL year",
      "Won the Heisman Trophy and a CFP national championship at LSU in 2019",
    ],
  },
  {
    name: "CeeDee Lamb",
    career: ["DAL","DAL","DAL","DAL","DAL"],
    positions: ["WR"], draftYear: 2020, college: "Oklahoma",
    notableFact: "Led the NFL in receiving yards in 2023 — the Cowboys' undisputed WR1.",
    clues: [
      "Won the Biletnikoff Award in 2019 at Oklahoma",
      "Became the team's top receiver after Amari Cooper was traded to Cleveland",
      "Was selected 17th overall by Dallas in 2020 — considered a draft-day steal",
      "Known for his exceptional yards after the catch ability",
      "Led the NFL in receiving yards in 2023 with 1,749",
    ],
  },
  {
    name: "Ja'Marr Chase",
    career: ["CIN","CIN","CIN","CIN"],
    positions: ["WR"], draftYear: 2021, college: "LSU",
    notableFact: "Won the OROY and broke the rookie receiving yards record — reunited with Joe Burrow.",
    clues: [
      "Was selected 5th overall in 2021 out of LSU",
      "Led the NFL in receiving yards in 2024",
      "Opted out of the 2020 college season and still went 5th overall in 2021",
      "Reunited with his LSU teammate Joe Burrow in Cincinnati",
      "Won the Offensive Rookie of the Year and broke the rookie receiving yards record in 2021",
    ],
  },
  {
    name: "Micah Parsons",
    career: ["DAL","DAL","DAL","DAL"],
    positions: ["LB","DE"], draftYear: 2021, college: "Penn State",
    notableFact: "Widely considered the best defensive player in the NFL — 3x DPOY finalist in his first 3 seasons.",
    clues: [
      "Played college football at Penn State under James Franklin",
      "Was selected 12th overall by the Dallas Cowboys in 2021",
      "Lines up at both linebacker and edge rusher depending on the package",
      "Has been a Defensive Player of the Year finalist in each of his first three NFL seasons",
      "Considered by many to be the best defensive player in the NFL",
    ],
  },
  {
    name: "Myles Garrett",
    career: ["CLE","CLE","CLE","CLE","CLE","CLE","CLE","CLE"],
    positions: ["DE"], draftYear: 2017, college: "Texas A&M",
    notableFact: "Won the NFL Defensive Player of the Year in 2023 — Cleveland's all-time sack leader.",
    clues: [
      "An avid dinosaur enthusiast — paleontology is a noted hobby of his",
      "Was suspended indefinitely in 2019 for striking Mason Rudolph with a helmet",
      "Cleveland's franchise leader in career sacks",
      "Won the NFL Defensive Player of the Year award in 2023",
      "Was selected #1 overall in 2017 out of Texas A&M",
    ],
  },
  {
    name: "T.J. Watt",
    career: ["PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT"],
    positions: ["LB"], draftYear: 2017, college: "Wisconsin",
    notableFact: "Tied the NFL single-season sack record with 22.5 in 2021 — won the DPOY that year.",
    clues: [
      "Was selected 30th overall in 2017 out of Wisconsin",
      "Younger brother of J.J. Watt — plays for the same team as his brother Derek Watt",
      "Won the NFL Defensive Player of the Year award in 2021",
      "Tied the NFL single-season sack record with 22.5 in 2021",
      "Plays for the Pittsburgh Steelers",
    ],
  },
  {
    name: "J.J. Watt",
    career: ["HOU","HOU","HOU","HOU","HOU","HOU","HOU","HOU","HOU","HOU","ARI","ARI","ARI"],
    positions: ["DE"], draftYear: 2011, college: "Wisconsin",
    notableFact: "3x NFL Defensive Player of the Year — the only player ever to win the award three times.",
    clues: [
      "Was selected 11th overall in 2011 out of Wisconsin",
      "Recorded 20.5 sacks in a single season in 2012",
      "Raised over $37 million for Hurricane Harvey relief efforts in 2017",
      "Played 10 seasons with the Houston Texans before signing with Arizona",
      "Won the NFL Defensive Player of the Year award three times — more than any other player ever",
    ],
  },
  {
    name: "Aaron Donald",
    career: ["LAR","LAR","LAR","LAR","LAR","LAR","LAR","LAR","LAR","LAR"],
    positions: ["DT"], draftYear: 2014, college: "Pittsburgh",
    notableFact: "3x DPOY — the only interior lineman to win it 3 times. Won the Super Bowl in his final season.",
    clues: [
      "Was selected 13th overall in 2014 out of the University of Pittsburgh",
      "Recorded double-digit sacks in multiple seasons from the defensive tackle position",
      "Won Super Bowl LVI with the Los Angeles Rams and retired shortly after",
      "Won the NFL Defensive Player of the Year award 3 times — a record for an interior lineman",
      "Considered by many to be the greatest interior defensive lineman in NFL history",
    ],
  },
  {
    name: "Von Miller",
    career: ["DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","DEN","LAR","BUF","BUF","BUF","BUF"],
    positions: ["LB"], draftYear: 2011, college: "Texas A&M",
    notableFact: "Super Bowl 50 MVP — his strip-sack in the 4th quarter sealed the championship.",
    clues: [
      "Was selected 2nd overall in 2011 out of Texas A&M",
      "Known for his elite spin move and first-step explosion off the edge",
      "Spent his first 10 seasons with the Denver Broncos",
      "Won a second Super Bowl ring with the Rams in Super Bowl LVI",
      "Named Super Bowl 50 MVP after two strip-sacks against Cam Newton",
    ],
  },
  {
    name: "Richard Sherman",
    career: ["SEA","SEA","SEA","SEA","SEA","SEA","SEA","SF","SF","SF","TB"],
    positions: ["CB"], draftYear: 2011, college: "Stanford",
    notableFact: "His tip in the 2013 NFC Championship is one of the most iconic plays in NFL history.",
    clues: [
      "Was selected 154th overall in 2011 — one of the greatest 5th-round picks in NFL history",
      "Gave a now-famous post-game rant to Erin Andrews after the NFC Championship Game",
      "Graduated from Stanford University — known for his outspoken intelligence",
      "Won Super Bowl XLVIII with the Seattle Seahawks as part of the 'Legion of Boom' secondary",
      "His tipped pass to Malcolm Smith in the 2013 NFC Championship sent Seattle to the Super Bowl",
    ],
  },
  {
    name: "Darrelle Revis",
    career: ["NYJ","NYJ","NYJ","NYJ","NYJ","NYJ","TB","NE","NYJ","NYJ","NYJ","KC","NYJ"],
    positions: ["CB"], draftYear: 2007, college: "Pittsburgh",
    notableFact: "'Revis Island' — had a 3-year stretch where he was arguably the most dominant CB ever.",
    clues: [
      "Was selected 14th overall in 2007 out of the University of Pittsburgh",
      "Was once the highest-paid cornerback in NFL history",
      "Has played for 5 different NFL teams throughout his career",
      "Won Super Bowl XLIX with the New England Patriots in his only season there",
      "Nicknamed 'Revis Island' — opposing teams avoided throwing his way entirely",
    ],
  },
  {
    name: "Khalil Mack",
    career: ["OAK","OAK","OAK","OAK","OAK","CHI","CHI","CHI","CHI","LAC","LAC","LAC","LAC"],
    positions: ["LB","DE"], draftYear: 2014, college: "Buffalo",
    notableFact: "First player ever to win both the NFL and collegiate Defensive Player of the Year awards.",
    clues: [
      "Was selected 5th overall in 2014 out of the University at Buffalo — a non-power-conference school",
      "Has recorded double-digit sacks with multiple different franchises",
      "First player to win both the NFL and collegiate DPOY awards",
      "Won the NFL Defensive Player of the Year award in 2016",
      "Was traded from Oakland to Chicago in a blockbuster deal that included multiple first-round picks",
    ],
  },
  {
    name: "George Kittle",
    career: ["SF","SF","SF","SF","SF","SF","SF","SF"],
    positions: ["TE"], draftYear: 2017, college: "Iowa",
    notableFact: "Set the single-season record for receiving yards by a TE with 1,377 in 2018.",
    clues: [
      "Was selected 146th overall in 2017 — a 5th-round steal from Iowa",
      "Plays for the San Francisco 49ers and is one of Kyle Shanahan's favorite weapons",
      "Famous for his intensity and wrestling-themed touchdown celebrations",
      "Known as one of the best blocking tight ends in NFL history in addition to his receiving",
      "Set the single-season record for receiving yards by a tight end in 2018",
    ],
  },
  {
    name: "Mark Andrews",
    career: ["BAL","BAL","BAL","BAL","BAL","BAL","BAL"],
    positions: ["TE"], draftYear: 2018, college: "Oklahoma",
    notableFact: "Led all TEs in receiving yards in 2021 — Lamar Jackson's most trusted target.",
    clues: [
      "Was selected 86th overall in 2018 out of Oklahoma",
      "Suffered a significant ankle injury in 2023 that limited his production",
      "Has type 1 diabetes — became a prominent advocate for diabetes awareness",
      "Has been Lamar Jackson's primary target throughout his Baltimore tenure",
      "Led all tight ends in receiving yards in 2021",
    ],
  },
  {
    name: "Cooper Kupp",
    career: ["LAR","LAR","LAR","LAR","LAR","LAR","LAR","LAR"],
    positions: ["WR"], draftYear: 2017, college: "Eastern Washington",
    notableFact: "Won Super Bowl LVI MVP and the receiver triple crown in 2021.",
    clues: [
      "Was selected 69th overall in 2017 out of Eastern Washington — a small FCS school",
      "Has missed significant time with injuries in recent seasons following his peak years",
      "Won the NFL receiver triple crown in 2021 — leading in receptions, yards, and TDs",
      "Named Super Bowl LVI MVP after the Rams defeated the Bengals",
      "Came from Eastern Washington — a small FCS school — to become an elite NFL receiver",
    ],
  },
  {
    name: "Brock Purdy",
    career: ["SF","SF","SF"],
    positions: ["QB"], draftYear: 2022, college: "Iowa State",
    notableFact: "'Mr. Irrelevant' in 2022 — led SF to the NFC Championship in his first full season.",
    clues: [
      "Played college football at Iowa State under Matt Campbell",
      "Has one of the highest career passer ratings through his first two seasons in NFL history",
      "Suffered an elbow injury in the NFC Championship but recovered for another strong season",
      "Led the San Francisco 49ers to the NFC Championship in his first full season",
      "Was 'Mr. Irrelevant' — the 262nd and final overall pick in the 2022 NFL Draft",
    ],
  },
  {
    name: "Jared Goff",
    career: ["LAR","LAR","LAR","LAR","LAR","DET","DET","DET","DET","DET"],
    positions: ["QB"], draftYear: 2016, college: "Cal",
    notableFact: "Led the Lions to the NFC Championship in 2023 — a massive career resurgence after being traded.",
    clues: [
      "Was selected #1 overall in 2016 out of Cal",
      "Had one of his most statistically impressive seasons in Detroit in 2023",
      "Reached Super Bowl LIII with the Rams but lost to New England",
      "Was traded from the Rams to Detroit in the Matthew Stafford blockbuster deal",
      "Led the Detroit Lions to the NFC Championship in 2023 — a franchise first in decades",
    ],
  },
  {
    name: "Drew Brees",
    career: ["SD","SD","SD","SD","SD","NO","NO","NO","NO","NO","NO","NO","NO","NO","NO"],
    positions: ["QB"], draftYear: 2001, college: "Purdue",
    notableFact: "Won Super Bowl XLIV — held the all-time passing yards record until Tom Brady broke it.",
    clues: [
      "Was selected 32nd overall in 2001 out of Purdue",
      "Became the face of New Orleans' recovery from Hurricane Katrina",
      "Was released by the Chargers after a severe shoulder injury — doctors doubted his recovery",
      "Won Super Bowl XLIV with the New Orleans Saints and was named the game's MVP",
      "Held the NFL record for career passing yards before Tom Brady broke it",
    ],
  },
  {
    name: "Cam Newton",
    career: ["CAR","CAR","CAR","CAR","CAR","CAR","CAR","CAR","CAR","NE","CAR"],
    positions: ["QB"], draftYear: 2011, college: "Auburn",
    notableFact: "Unanimous MVP in 2015 — led the Panthers to a 15-1 record and the Super Bowl.",
    clues: [
      "Was selected #1 overall in 2011",
      "Won the Heisman Trophy and a national championship at Auburn in 2010",
      "The most powerful running QB of his era — famous for his Superman TD celebrations",
      "Lost Super Bowl 50 to the Denver Broncos",
      "Won unanimous NFL MVP in 2015 after leading the Panthers to a 15-1 regular season record",
    ],
  },
  {
    name: "Russell Wilson",
    career: ["SEA","SEA","SEA","SEA","SEA","SEA","SEA","SEA","SEA","SEA","DEN","DEN","DEN","PIT"],
    positions: ["QB"], draftYear: 2012, college: "Wisconsin",
    notableFact: "Won Super Bowl XLVIII with Seattle — one of the most decorated QBs of his era.",
    clues: [
      "Was selected 75th overall in 2012 and also played minor league baseball",
      "Later signed with the Pittsburgh Steelers after being released by Denver",
      "Was traded from Seattle to Denver in a blockbuster deal after 10 seasons",
      "Was not given the ball on the 1-yard line in Super Bowl XLIX — resulting in a pick that lost the game",
      "Won Super Bowl XLVIII with the Seattle Seahawks",
    ],
  },
  {
    name: "Philip Rivers",
    career: ["SD","SD","SD","SD","SD","SD","SD","SD","SD","SD","SD","SD","SD","SD","LAC","LAC","IND"],
    positions: ["QB"], draftYear: 2004, college: "NC State",
    notableFact: "Played 16 seasons with the Chargers — one of the most loyal franchise QBs in NFL history.",
    clues: [
      "Was selected 4th overall in 2004 out of NC State",
      "Was swapped on draft night — the Giants drafted him, then traded him for Eli Manning",
      "Has 9 children with his wife Tiffany and is known for his devout Catholic faith",
      "Finished his career with 1 season in Indianapolis",
      "Played 16 seasons with the Chargers — one of the NFL's most loyal franchise QBs",
    ],
  },
  {
    name: "Eli Manning",
    career: ["NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG","NYG"],
    positions: ["QB"], draftYear: 2004, college: "Ole Miss",
    notableFact: "2x Super Bowl MVP — upset the Patriots twice as massive underdogs.",
    clues: [
      "Played all 16 seasons with the New York Giants",
      "Was swapped on draft night — the Chargers selected him #1, then traded him to the Giants for Philip Rivers",
      "Famous for the David Tyree 'Helmet Catch' game vs. the Patriots in Super Bowl XLII",
      "Younger brother of Peyton Manning",
      "Named Super Bowl MVP twice — both times upsetting the heavily favored New England Patriots",
    ],
  },
  {
    name: "Ben Roethlisberger",
    career: ["PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT","PIT"],
    positions: ["QB"], draftYear: 2004, college: "Miami (OH)",
    notableFact: "Won 2 Super Bowls with the Steelers — played all 18 seasons in Pittsburgh.",
    clues: [
      "Was selected 11th overall in 2004 out of Miami of Ohio",
      "Known for his incredible pocket presence and ability to shed tacklers",
      "Played all 18 seasons of his NFL career with the Pittsburgh Steelers",
      "Named the youngest QB to win a Super Bowl after Super Bowl XL",
      "Won 2 Super Bowls with the Pittsburgh Steelers",
    ],
  },
  {
    name: "Tony Romo",
    career: ["DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL","DAL"],
    positions: ["QB"], draftYear: 2003, college: "Eastern Illinois",
    notableFact: "Undrafted from a small school — went to 4 Pro Bowls but never made it past the divisional round.",
    clues: [
      "Became one of the most acclaimed CBS NFL broadcast analysts after retiring",
      "Played 14 seasons with the Dallas Cowboys — never had a losing regular season as a starter",
      "Famous for botching a field goal hold in a 2006 wild card game against Seattle",
      "Made 4 Pro Bowls despite never winning a playoff game beyond the divisional round",
      "Signed as an undrafted free agent out of Eastern Illinois",
    ],
  },
  {
    name: "Matthew Stafford",
    career: ["DET","DET","DET","DET","DET","DET","DET","DET","DET","DET","DET","DET","LAR","LAR","LAR","LAR"],
    positions: ["QB"], draftYear: 2009, college: "Georgia",
    notableFact: "Won Super Bowl LVI with the Rams after 12 seasons in Detroit without a single playoff win.",
    clues: [
      "Was selected #1 overall in 2009 out of Georgia",
      "Named to the Pro Bowl following his Super Bowl season",
      "Was traded to the Rams in a blockbuster deal alongside multiple draft picks",
      "Spent 12 seasons with the Detroit Lions without advancing past the Wild Card round",
      "Won Super Bowl LVI with the Los Angeles Rams — his first championship",
    ],
  },
  {
    name: "Fred Warner",
    career: ["SF","SF","SF","SF","SF","SF","SF"],
    positions: ["LB"], draftYear: 2018, college: "BYU",
    notableFact: "The highest-paid linebacker in NFL history — considered the best at his position.",
    clues: [
      "Was selected 70th overall in 2018 out of BYU",
      "Known for his coverage ability, run stopping, and football IQ",
      "A central figure in Kyle Shanahan's dominant 49ers defense",
      "Considered by many the best linebacker in the NFL",
      "Signed the largest contract in NFL history for a linebacker",
    ],
  },
  {
    name: "Bobby Wagner",
    career: ["SEA","SEA","SEA","SEA","SEA","SEA","SEA","SEA","SEA","SEA","LAR","SEA","SEA"],
    positions: ["LB"], draftYear: 2012, college: "Utah State",
    notableFact: "8x All-Pro and Super Bowl champion — the most decorated LB of his era.",
    clues: [
      "Was selected 47th overall in 2012 out of Utah State",
      "Briefly played for the Los Angeles Rams before returning to Seattle",
      "Was a key part of Seattle's 'Legion of Boom' defensive era",
      "Won Super Bowl XLVIII with the Seattle Seahawks",
      "One of the most decorated linebackers of his generation — 8x All-Pro",
    ],
  },
  {
    name: "Derwin James",
    career: ["LAC","LAC","LAC","LAC","LAC","LAC","LAC"],
    positions: ["S"], draftYear: 2018, college: "Florida State",
    notableFact: "Signed the richest contract ever for a safety — considered the most complete at his position.",
    clues: [
      "Was selected 17th overall in 2018 out of Florida State",
      "Missed his entire second NFL season due to a knee injury",
      "Lines up at multiple positions — safety, linebacker, and slot corner",
      "Considered by many the most complete and versatile safety in the NFL",
      "Signed the largest contract in NFL history for a safety",
    ],
  },
  {
    name: "Jalen Ramsey",
    career: ["JAX","JAX","JAX","JAX","LAR","LAR","LAR","LAR","LAR","MIA"],
    positions: ["CB"], draftYear: 2016, college: "Florida State",
    notableFact: "Won Super Bowl LVI with the Rams — one of the most gifted corners of his generation.",
    clues: [
      "Was selected 5th overall in 2016 out of Florida State",
      "Can line up at multiple defensive back positions due to his elite athleticism",
      "Known for being outspoken — gave a viral interview criticizing multiple NFL quarterbacks",
      "Was traded from Jacksonville to LA in 2019 for two first-round picks",
      "Won Super Bowl LVI with the Los Angeles Rams",
    ],
  },
  {
    name: "DK Metcalf",
    career: ["SEA","SEA","SEA","SEA","SEA","SEA","SEA"],
    positions: ["WR"], draftYear: 2019, college: "Ole Miss",
    notableFact: "His NFL Combine workout — 6'4\", 228 lbs, 4.33 speed — is considered the most impressive ever.",
    clues: [
      "Was selected 64th overall in 2019 after slipping due to injury concerns at Ole Miss",
      "Has competed in USATF 100m open national championships as a sprinter",
      "Chased down a cornerback after a would-be interception in 2020 — a viral moment",
      "Forms a dynamic duo with Tyler Lockett in Seattle",
      "His NFL Combine workout — 6'4, 228 lbs, 4.33 40-yard dash — is considered one of the greatest ever",
    ],
  },
  {
    name: "Jayden Daniels",
    career: ["WAS","WAS"],
    positions: ["QB"], draftYear: 2024, college: "LSU",
    notableFact: "Won the Heisman at LSU and led Washington to the NFC Championship in his rookie year.",
    clues: [
      "Was selected 2nd overall in the 2024 NFL Draft",
      "Transferred from Arizona State to LSU where he played under Brian Kelly",
      "One of the most dynamic dual-threat QBs to enter the NFL in recent years",
      "Led the Washington Commanders to the NFC Championship in his rookie year",
      "Won the Heisman Trophy at LSU in 2023",
    ],
  },
  {
    name: "C.J. Stroud",
    career: ["HOU","HOU"],
    positions: ["QB"], draftYear: 2023, college: "Ohio State",
    notableFact: "Won Offensive Rookie of the Year in 2023 and led Houston to the playoffs.",
    clues: [
      "Was selected 2nd overall in the 2023 NFL Draft",
      "Played college football at Ohio State under Ryan Day",
      "Had one of the most impressive statistical rookie QB seasons in NFL history",
      "Led the Houston Texans to the playoffs in his very first NFL season",
      "Won the Offensive Rookie of the Year award in 2023",
    ],
  },
  {
    name: "Antonio Gates",
    career: ["SD","SD","SD","SD","SD","SD","SD","SD","SD","SD","SD","SD","SD","LAC","LAC","LAC"],
    positions: ["TE"], draftYear: 2003, college: "Kent State",
    notableFact: "Never played college football — went from basketball walk-on to 8x Pro Bowl TE.",
    clues: [
      "Was selected to 8 Pro Bowls despite never being drafted",
      "Had a celebrated partnership with QB Philip Rivers that lasted over a decade",
      "Spent his entire 16-year career with the San Diego/Los Angeles Chargers",
      "Signed as an undrafted free agent and became one of the greatest TEs of his era",
      "Never played college football — was a basketball player at Kent State",
    ],
  },
  {
    name: "Jaylen Waddle",
    career: ["MIA","MIA","MIA","MIA"],
    positions: ["WR"], draftYear: 2021, college: "Alabama",
    notableFact: "Set the NFL record for receptions by a rookie with 104 in 2021.",
    clues: [
      "Was selected 6th overall in 2021 out of Alabama",
      "Suffered a significant ankle injury in the Alabama-Tennessee game in 2020",
      "Forms one of the fastest and most explosive receiver duos in the NFL with Tyreek Hill",
      "Reunited with his college QB Tua Tagovailoa in Miami",
      "Set the NFL record for receptions by a rookie with 104 in 2021",
    ],
  },
  {
    name: "Puka Nacua",
    career: ["LAR","LAR"],
    positions: ["WR"], draftYear: 2023, college: "BYU",
    notableFact: "Set NFL records for receptions and yards in first 5 career games — a 5th-round steal.",
    clues: [
      "Was selected 177th overall in 2023 out of BYU — a massive 5th-round value pick",
      "Suffered a serious knee injury in 2024 that cut his sophomore season short",
      "Comes from a football family — multiple brothers played college and professional football",
      "One of the biggest surprise stars of the 2023 NFL season",
      "Set NFL records for receptions and receiving yards in a player's first five career games",
    ],
  },
  {
    name: "Jordan Love",
    career: ["GB","GB","GB","GB","GB"],
    positions: ["QB"], draftYear: 2020, college: "Utah State",
    notableFact: "Waited 3+ years as Aaron Rodgers' backup before becoming Green Bay's franchise QB.",
    clues: [
      "Was selected 26th overall in 2020 out of Utah State",
      "Signed a massive contract extension with Green Bay ahead of the 2024 season",
      "Led the Packers to the playoffs in his first full season as a starter in 2023",
      "Waited over 3 seasons as Aaron Rodgers' backup before getting his starting opportunity",
      "Green Bay's franchise QB after the Rodgers era",
    ],
  },
  {
    name: "Sam Darnold",
    career: ["NYJ","NYJ","NYJ","CAR","SF","MIN","MIN"],
    positions: ["QB"], draftYear: 2018, college: "USC",
    notableFact: "Surprised the NFL with an 11-0 start leading the Vikings in 2024 after years of struggles.",
    clues: [
      "Was selected 3rd overall in 2018 out of USC",
      "Famously said he was 'seeing ghosts' during a struggling performance against the Patriots in 2019",
      "Was a highly touted recruit who became USC's starter as a true freshman",
      "Had struggled for years with the Jets and Panthers before reviving his career in Minnesota",
      "Led the Minnesota Vikings to the best NFC start in 2024 as a surprise starter",
    ],
  },
];