import type { DraftPlayer } from './types';

type RawPlayer = Omit<DraftPlayer, 'headshot'>;

export const DRAFT_DATA: Record<number, RawPlayer[]> = {
  2016: [
    { id:'16-01', name:'Jalen Ramsey',    position:'CB',   actualPick:5,   actualRound:1, draftedBy:'JAX', careerGrade:'S', careerNote:'6× Pro Bowl, 3× All-Pro — best CB of his era' },
    { id:'16-02', name:'Joey Bosa',       position:'EDGE', actualPick:3,   actualRound:1, draftedBy:'SD',  careerGrade:'S', careerNote:'5× Pro Bowl, DROY 2016, elite pass rusher' },
    { id:'16-03', name:'Dak Prescott',    position:'QB',   actualPick:135, actualRound:4, draftedBy:'DAL', careerGrade:'S', careerNote:'4× Pro Bowl, franchise QB of Cowboys' },
    { id:'16-04', name:'Derrick Henry',   position:'RB',   actualPick:45,  actualRound:2, draftedBy:'TEN', careerGrade:'S', careerNote:'2× rushing champ, 2,000-yd season, MVP candidate' },
    { id:'16-05', name:'Michael Thomas',  position:'WR',   actualPick:47,  actualRound:2, draftedBy:'NO',  careerGrade:'S', careerNote:'Single-season reception record (149), All-Pro' },
    { id:'16-06', name:'Xavien Howard',   position:'CB',   actualPick:38,  actualRound:2, draftedBy:'MIA', careerGrade:'S', careerNote:'3× Pro Bowl, 2× NFL interception leader' },
    { id:'16-07', name:'Laremy Tunsil',   position:'OT',   actualPick:13,  actualRound:1, draftedBy:'MIA', careerGrade:'A', careerNote:'3× Pro Bowl, elite LT — slid due to draft-night controversy' },
    { id:'16-08', name:'Ezekiel Elliott', position:'RB',   actualPick:4,   actualRound:1, draftedBy:'DAL', careerGrade:'A', careerNote:'3× rushing champ, 4× Pro Bowl' },
    { id:'16-09', name:'Hunter Henry',    position:'TE',   actualPick:35,  actualRound:2, draftedBy:'SD',  careerGrade:'A', careerNote:'2× Pro Bowl, elite receiving TE' },
    { id:'16-10', name:'Ryan Kelly',      position:'C',    actualPick:18,  actualRound:1, draftedBy:'IND', careerGrade:'A', careerNote:'Pro Bowl center, stalwart starter' },
    { id:'16-11', name:'Ronnie Stanley',  position:'OT',   actualPick:6,   actualRound:1, draftedBy:'BAL', careerGrade:'A', careerNote:'Pro Bowl LT, 2020 All-Pro before injury' },
    { id:'16-12', name:'Jack Conklin',    position:'OT',   actualPick:8,   actualRound:1, draftedBy:'TEN', careerGrade:'A', careerNote:'3× Pro Bowl, Super Bowl appearance' },
    { id:'16-13', name:'Tyler Boyd',      position:'WR',   actualPick:55,  actualRound:2, draftedBy:'CIN', careerGrade:'A', careerNote:'Consistent WR2, 1,000-yd seasons' },
    { id:'16-14', name:'Austin Hooper',   position:'TE',   actualPick:81,  actualRound:3, draftedBy:'ATL', careerGrade:'B', careerNote:'2× Pro Bowl TE' },
    { id:'16-15', name:'Emmanuel Ogbah',  position:'EDGE', actualPick:32,  actualRound:1, draftedBy:'CLE', careerGrade:'B', careerNote:'12 sacks in 2021, solid starter' },
    { id:'16-16', name:'Jared Goff',      position:'QB',   actualPick:1,   actualRound:1, draftedBy:'LAR', careerGrade:'B', careerNote:'Super Bowl appearance, Pro Bowl, long career' },
    { id:'16-17', name:'Leonard Floyd',   position:'EDGE', actualPick:9,   actualRound:1, draftedBy:'CHI', careerGrade:'B', careerNote:'9.5 sacks, consistent starter' },
    { id:'16-18', name:'Sterling Shepard',position:'WR',   actualPick:40,  actualRound:2, draftedBy:'NYG', careerGrade:'B', careerNote:'Solid WR2, 8+ seasons' },
    { id:'16-19', name:'Kenyan Drake',    position:'RB',   actualPick:73,  actualRound:3, draftedBy:'MIA', careerGrade:'B', careerNote:'Flash of greatness, 2020 AZ 10 TDs' },
    { id:'16-20', name:'Vonn Bell',       position:'S',    actualPick:61,  actualRound:2, draftedBy:'NO',  careerGrade:'B', careerNote:'Long-time starting safety' },
    { id:'16-21', name:'William Jackson', position:'CB',   actualPick:24,  actualRound:1, draftedBy:'CIN', careerGrade:'B', careerNote:'Solid starting CB' },
    { id:'16-22', name:'Carson Wentz',    position:'QB',   actualPick:2,   actualRound:1, draftedBy:'PHI', careerGrade:'C', careerNote:'MVP candidate 2017, injury and inconsistency derailed him' },
    { id:'16-23', name:'Eli Apple',       position:'CB',   actualPick:10,  actualRound:1, draftedBy:'NYG', careerGrade:'C', careerNote:'Key SB moment, inconsistent starter' },
    { id:'16-24', name:'Shaq Lawson',     position:'EDGE', actualPick:19,  actualRound:1, draftedBy:'BUF', careerGrade:'C', careerNote:'Serviceable but underwhelmed as R1 pick' },
    { id:'16-25', name:'Germain Ifedi',   position:'OG',   actualPick:31,  actualRound:1, draftedBy:'SEA', careerGrade:'C', careerNote:'Long career, starter-level' },
    { id:'16-26', name:'Corey Coleman',   position:'WR',   actualPick:15,  actualRound:1, draftedBy:'CLE', careerGrade:'D', careerNote:'Injuries wrecked a promising start' },
    { id:'16-27', name:'Paxton Lynch',    position:'QB',   actualPick:26,  actualRound:1, draftedBy:'DEN', careerGrade:'D', careerNote:'One of the worst R1 QBs in recent memory' },
    { id:'16-28', name:'Laquon Treadwell',position:'WR',   actualPick:23,  actualRound:1, draftedBy:'MIN', careerGrade:'D', careerNote:'Massive bust, near-zero NFL impact' },
    { id:'16-29', name:'Robert Nkemdiche',position:'DT',   actualPick:29,  actualRound:1, draftedBy:'ARI', careerGrade:'D', careerNote:'Out of league by year 3' },
    { id:'16-30', name:'Braxton Miller',  position:'WR',   actualPick:85,  actualRound:3, draftedBy:'HOU', careerGrade:'D', careerNote:'Never transitioned from QB to WR' },
  ],
  2017: [
    { id:'17-01', name:'Patrick Mahomes',    position:'QB',   actualPick:10,  actualRound:1, draftedBy:'KC',  careerGrade:'S', careerNote:'3× SB champ, 2× MVP, redefining the QB position' },
    { id:'17-02', name:'T.J. Watt',          position:'EDGE', actualPick:30,  actualRound:1, draftedBy:'PIT', careerGrade:'S', careerNote:'4× DPOY, sack record co-holder, greatest defender of his era' },
    { id:'17-03', name:'Alvin Kamara',       position:'RB',   actualPick:67,  actualRound:3, draftedBy:'NO',  careerGrade:'S', careerNote:'5× Pro Bowl, ROTY 2017, elite dual-threat' },
    { id:'17-04', name:'Christian McCaffrey',position:'RB',   actualPick:8,   actualRound:1, draftedBy:'CAR', careerGrade:'S', careerNote:'2,000-yd scrimmage, Super Bowl, versatile star' },
    { id:'17-05', name:'Marshon Lattimore',  position:'CB',   actualPick:11,  actualRound:1, draftedBy:'NO',  careerGrade:'S', careerNote:'4× Pro Bowl, DROY 2017, elite corner' },
    { id:'17-06', name:'Myles Garrett',      position:'EDGE', actualPick:1,   actualRound:1, draftedBy:'CLE', careerGrade:'S', careerNote:'6× Pro Bowl, multiple sack titles, perennial DPOY' },
    { id:'17-07', name:'Cooper Kupp',        position:'WR',   actualPick:69,  actualRound:3, draftedBy:'LAR', careerGrade:'S', careerNote:'Super Bowl MVP, triple crown WR, All-Pro' },
    { id:'17-08', name:'Chris Godwin',       position:'WR',   actualPick:84,  actualRound:3, draftedBy:'TB',  careerGrade:'S', careerNote:'3× Pro Bowl, elite slot WR, Super Bowl champ' },
    { id:'17-09', name:'Darius Leonard',     position:'LB',   actualPick:36,  actualRound:2, draftedBy:'IND', careerGrade:'S', careerNote:'2× DPOY, 3× All-Pro, elite ILB' },
    { id:'17-10', name:'Aaron Jones',        position:'RB',   actualPick:182, actualRound:5, draftedBy:'GB',  careerGrade:'A', careerNote:'2× Pro Bowl, consistent 10+ TD seasons' },
    { id:'17-11', name:'Austin Ekeler',      position:'RB',   actualPick:0,   actualRound:0, draftedBy:'LAC', careerGrade:'A', careerNote:'UDFA → 3× Pro Bowl, PPR machine' },
    { id:'17-12', name:'Ryan Ramczyk',       position:'OT',   actualPick:32,  actualRound:1, draftedBy:'NO',  careerGrade:'A', careerNote:'3× Pro Bowl, elite RT' },
    { id:'17-13', name:"Tre'Davious White",  position:'CB',   actualPick:27,  actualRound:1, draftedBy:'BUF', careerGrade:'A', careerNote:'3× Pro Bowl, All-Pro 2019' },
    { id:'17-14', name:'JuJu Smith-Schuster',position:'WR',   actualPick:62,  actualRound:2, draftedBy:'PIT', careerGrade:'A', careerNote:'1,400-yd season, consistent WR2' },
    { id:'17-15', name:'Zach Cunningham',    position:'LB',   actualPick:57,  actualRound:2, draftedBy:'HOU', careerGrade:'A', careerNote:'Led NFL in tackles, All-Pro 2020' },
    { id:'17-16', name:'Kareem Hunt',        position:'RB',   actualPick:86,  actualRound:3, draftedBy:'KC',  careerGrade:'A', careerNote:'Rushing champ rookie year, long career' },
    { id:'17-17', name:'Jabrill Peppers',    position:'S',    actualPick:25,  actualRound:1, draftedBy:'CLE', careerGrade:'B', careerNote:'Long-time starting safety' },
    { id:'17-18', name:'Evan Engram',        position:'TE',   actualPick:23,  actualRound:1, draftedBy:'NYG', careerGrade:'B', careerNote:'Pro Bowl 2022, reliable TE' },
    { id:'17-19', name:'Deshaun Watson',     position:'QB',   actualPick:12,  actualRound:1, draftedBy:'HOU', careerGrade:'B', careerNote:'Elite talent before off-field issues' },
    { id:'17-20', name:'Mike Williams',      position:'WR',   actualPick:7,   actualRound:1, draftedBy:'LAC', careerGrade:'B', careerNote:'Solid deep threat, 1,000-yd season' },
    { id:'17-21', name:'Corey Davis',        position:'WR',   actualPick:5,   actualRound:1, draftedBy:'TEN', careerGrade:'C', careerNote:'Disappointing as #5 pick, serviceable' },
    { id:'17-22', name:'O.J. Howard',        position:'TE',   actualPick:19,  actualRound:1, draftedBy:'TB',  careerGrade:'C', careerNote:'Flashes of brilliance, injuries stalled career' },
    { id:'17-23', name:'Gareon Conley',      position:'CB',   actualPick:24,  actualRound:1, draftedBy:'OAK', careerGrade:'D', careerNote:'Never lived up to R1 billing' },
    { id:'17-24', name:'DeShone Kizer',      position:'QB',   actualPick:52,  actualRound:2, draftedBy:'CLE', careerGrade:'D', careerNote:'Failed starter in Cleveland' },
    { id:'17-25', name:'Takkarist McKinley', position:'EDGE', actualPick:26,  actualRound:1, draftedBy:'ATL', careerGrade:'D', careerNote:'Disappointing, out of league quickly' },
  ],
  2018: [
    { id:'18-01', name:'Quenton Nelson',    position:'OG',   actualPick:6,   actualRound:1, draftedBy:'IND', careerGrade:'S', careerNote:'5× All-Pro, best guard in NFL history candidate' },
    { id:'18-02', name:'Lamar Jackson',     position:'QB',   actualPick:32,  actualRound:1, draftedBy:'BAL', careerGrade:'S', careerNote:'2× MVP (unanimous 2019), franchise QB' },
    { id:'18-03', name:'Minkah Fitzpatrick',position:'S',    actualPick:11,  actualRound:1, draftedBy:'MIA', careerGrade:'S', careerNote:'3× All-Pro, elite ball-hawking safety' },
    { id:'18-04', name:'Nick Chubb',        position:'RB',   actualPick:35,  actualRound:2, draftedBy:'CLE', careerGrade:'S', careerNote:'4× Pro Bowl, elite runner, 1,000+ every full season' },
    { id:'18-05', name:'Roquan Smith',      position:'LB',   actualPick:8,   actualRound:1, draftedBy:'CHI', careerGrade:'S', careerNote:'3× Pro Bowl, 2× All-Pro, elite ILB' },
    { id:'18-06', name:'Josh Allen',        position:'QB',   actualPick:7,   actualRound:1, draftedBy:'BUF', careerGrade:'S', careerNote:'5× Pro Bowl, MVP frontrunner, franchise QB' },
    { id:'18-07', name:'Saquon Barkley',    position:'RB',   actualPick:2,   actualRound:1, draftedBy:'NYG', careerGrade:'A', careerNote:'ROTY 2018, 2,000-yd season 2023, Pro Bowl' },
    { id:'18-08', name:'Derwin James',      position:'S',    actualPick:17,  actualRound:1, draftedBy:'LAC', careerGrade:'S', careerNote:'3× Pro Bowl, All-Pro, elite safety' },
    { id:'18-09', name:'Jessie Bates III',  position:'S',    actualPick:54,  actualRound:2, draftedBy:'CIN', careerGrade:'A', careerNote:'3× Pro Bowl, All-Pro safety' },
    { id:'18-10', name:'D.J. Moore',        position:'WR',   actualPick:24,  actualRound:1, draftedBy:'CAR', careerGrade:'A', careerNote:'3× 1,000-yd seasons, consistent WR1' },
    { id:'18-11', name:'Calvin Ridley',     position:'WR',   actualPick:26,  actualRound:1, draftedBy:'ATL', careerGrade:'A', careerNote:'1,374-yd season, Pro Bowl talent' },
    { id:'18-12', name:'Frank Ragnow',      position:'C',    actualPick:20,  actualRound:1, draftedBy:'DET', careerGrade:'A', careerNote:'3× Pro Bowl, elite center' },
    { id:'18-13', name:'Vita Vea',          position:'DT',   actualPick:12,  actualRound:1, draftedBy:'TB',  careerGrade:'A', careerNote:'Super Bowl champ, Pro Bowl DT' },
    { id:'18-14', name:'Harold Landry',     position:'EDGE', actualPick:41,  actualRound:2, draftedBy:'TEN', careerGrade:'A', careerNote:'14.5 sacks in 2021, Pro Bowl edge' },
    { id:'18-15', name:"Da'Ron Payne",      position:'DT',   actualPick:13,  actualRound:1, draftedBy:'WAS', careerGrade:'A', careerNote:'14 sacks in 2022, Pro Bowl DT' },
    { id:'18-16', name:'Courtland Sutton',  position:'WR',   actualPick:40,  actualRound:2, draftedBy:'DEN', careerGrade:'A', careerNote:'Pro Bowl, 1,112-yd season with weak QBs' },
    { id:'18-17', name:'Bradley Chubb',     position:'EDGE', actualPick:5,   actualRound:1, draftedBy:'DEN', careerGrade:'B', careerNote:'14.5 sacks rookie year, injuries hampered' },
    { id:'18-18', name:'Baker Mayfield',    position:'QB',   actualPick:1,   actualRound:1, draftedBy:'CLE', careerGrade:'B', careerNote:'SB LVI starter, had highs and lows' },
    { id:'18-19', name:'Tremaine Edmunds',  position:'LB',   actualPick:16,  actualRound:1, draftedBy:'BUF', careerGrade:'B', careerNote:'Long-time starter, Pro Bowl' },
    { id:'18-20', name:'DJ Chark',          position:'WR',   actualPick:61,  actualRound:2, draftedBy:'JAX', careerGrade:'B', careerNote:'1,000-yd season 2019, solid WR2' },
    { id:'18-21', name:'Sam Darnold',       position:'QB',   actualPick:3,   actualRound:1, draftedBy:'NYJ', careerGrade:'C', careerNote:'Journeyman, disappointing for #3 pick' },
    { id:'18-22', name:'Josh Rosen',        position:'QB',   actualPick:10,  actualRound:1, draftedBy:'ARI', careerGrade:'D', careerNote:'Traded in year 2, out of league quickly' },
    { id:'18-23', name:'Anthony Miller',    position:'WR',   actualPick:51,  actualRound:2, draftedBy:'CHI', careerGrade:'D', careerNote:'Disappointing, out of league quickly' },
  ],
  2019: [
    { id:'19-01', name:'Nick Bosa',          position:'EDGE', actualPick:2,   actualRound:1, draftedBy:'SF',  careerGrade:'S', careerNote:'2× DPOY, 4× Pro Bowl, dominant pass rusher' },
    { id:'19-02', name:'Quinnen Williams',   position:'DT',   actualPick:3,   actualRound:1, draftedBy:'NYJ', careerGrade:'S', careerNote:'12 sacks 2022, 2× Pro Bowl, elite interior' },
    { id:'19-03', name:'Deebo Samuel',       position:'WR',   actualPick:36,  actualRound:2, draftedBy:'SF',  careerGrade:'S', careerNote:'2× Pro Bowl, unique rushing/receiving weapon' },
    { id:'19-04', name:'A.J. Brown',         position:'WR',   actualPick:51,  actualRound:2, draftedBy:'TEN', careerGrade:'S', careerNote:'3× Pro Bowl, 1,400-yd seasons, elite WR1' },
    { id:'19-05', name:'DK Metcalf',         position:'WR',   actualPick:64,  actualRound:2, draftedBy:'SEA', careerGrade:'S', careerNote:'3× Pro Bowl, elite contested-catch WR' },
    { id:'19-06', name:'Terry McLaurin',     position:'WR',   actualPick:76,  actualRound:3, draftedBy:'WAS', careerGrade:'A', careerNote:'3× Pro Bowl, elite route runner' },
    { id:'19-07', name:'Josh Jacobs',        position:'RB',   actualPick:24,  actualRound:1, draftedBy:'OAK', careerGrade:'A', careerNote:'2× Pro Bowl, 2022 rushing champ (1,653 yds)' },
    { id:'19-08', name:'Kyler Murray',       position:'QB',   actualPick:1,   actualRound:1, draftedBy:'ARI', careerGrade:'A', careerNote:'2× Pro Bowl, ROTY 2019, exciting dual-threat' },
    { id:'19-09', name:'T.J. Hockenson',     position:'TE',   actualPick:8,   actualRound:1, draftedBy:'DET', careerGrade:'A', careerNote:'2× Pro Bowl, elite receiving TE' },
    { id:'19-10', name:'Christian Wilkins',  position:'DT',   actualPick:13,  actualRound:1, draftedBy:'MIA', careerGrade:'A', careerNote:'Pro Bowl DT, 11 sacks in 2023' },
    { id:'19-11', name:'Michael Pittman Jr.',position:'WR',   actualPick:34,  actualRound:2, draftedBy:'IND', careerGrade:'A', careerNote:'2× Pro Bowl, 1,152-yd season' },
    { id:'19-12', name:'Jawaan Taylor',      position:'OT',   actualPick:35,  actualRound:2, draftedBy:'JAX', careerGrade:'A', careerNote:'Super Bowl LVI starter, quality RT' },
    { id:'19-13', name:'Rashan Gary',        position:'EDGE', actualPick:12,  actualRound:1, draftedBy:'GB',  careerGrade:'A', careerNote:'9.5 sacks, emerging star pass rusher' },
    { id:'19-14', name:'Brian Burns',        position:'EDGE', actualPick:16,  actualRound:1, draftedBy:'CAR', careerGrade:'A', careerNote:'Consistent double-digit sack threat' },
    { id:'19-15', name:'Miles Sanders',      position:'RB',   actualPick:53,  actualRound:2, draftedBy:'PHI', careerGrade:'B', careerNote:'1,269-yd season, consistent starter' },
    { id:'19-16', name:'Marquise Brown',     position:'WR',   actualPick:25,  actualRound:1, draftedBy:'BAL', careerGrade:'B', careerNote:'1,000-yd season with ARI' },
    { id:'19-17', name:'Daniel Jones',       position:'QB',   actualPick:6,   actualRound:1, draftedBy:'NYG', careerGrade:'C', careerNote:'Starter, mixed results, injuries' },
    { id:'19-18', name:'Clelin Ferrell',     position:'EDGE', actualPick:4,   actualRound:1, draftedBy:'OAK', careerGrade:'D', careerNote:'Disappointing #4 overall pick' },
    { id:'19-19', name:'Devin Bush',         position:'LB',   actualPick:10,  actualRound:1, draftedBy:'PIT', careerGrade:'C', careerNote:'Injury, failed to meet R1 expectations' },
    { id:'19-20', name:'Andre Dillard',      position:'OT',   actualPick:22,  actualRound:1, draftedBy:'PHI', careerGrade:'D', careerNote:'Injuries destroyed career' },
  ],
  2020: [
    { id:'20-01', name:'Justin Jefferson',  position:'WR',   actualPick:22,  actualRound:1, draftedBy:'MIN', careerGrade:'S', careerNote:'4× Pro Bowl, fastest 4,000-yd WR, 2× All-Pro' },
    { id:'20-02', name:'Joe Burrow',        position:'QB',   actualPick:1,   actualRound:1, draftedBy:'CIN', careerGrade:'S', careerNote:'2× Pro Bowl, Super Bowl LVI, elite passer' },
    { id:'20-03', name:'CeeDee Lamb',       position:'WR',   actualPick:17,  actualRound:1, draftedBy:'DAL', careerGrade:'S', careerNote:'3× Pro Bowl, 1,749-yd season, All-Pro' },
    { id:'20-04', name:'Jonathan Taylor',   position:'RB',   actualPick:41,  actualRound:2, draftedBy:'IND', careerGrade:'S', careerNote:'3× Pro Bowl, 2021 rushing champ (1,811 yds)' },
    { id:'20-05', name:'Andrew Thomas',     position:'OT',   actualPick:4,   actualRound:1, draftedBy:'NYG', careerGrade:'S', careerNote:'3× Pro Bowl, All-Pro LT' },
    { id:'20-06', name:'Tristan Wirfs',     position:'OT',   actualPick:13,  actualRound:1, draftedBy:'TB',  careerGrade:'S', careerNote:'3× Pro Bowl, All-Pro, Super Bowl champ' },
    { id:'20-07', name:'Brandon Aiyuk',     position:'WR',   actualPick:25,  actualRound:1, draftedBy:'SF',  careerGrade:'S', careerNote:'2× Pro Bowl, Super Bowl appearance, elite WR1' },
    { id:'20-08', name:'Tee Higgins',       position:'WR',   actualPick:33,  actualRound:2, draftedBy:'CIN', careerGrade:'A', careerNote:'2× 1,000-yd WR, Super Bowl appearance' },
    { id:'20-09', name:'Justin Madubuike',  position:'DT',   actualPick:71,  actualRound:3, draftedBy:'BAL', careerGrade:'A', careerNote:'13 sacks in 2023, Pro Bowl' },
    { id:'20-10', name:'Jordan Love',       position:'QB',   actualPick:26,  actualRound:1, draftedBy:'GB',  careerGrade:'A', careerNote:'2× Pro Bowl, NFC title game, emerging franchise QB' },
    { id:'20-11', name:'Chase Young',       position:'EDGE', actualPick:2,   actualRound:1, draftedBy:'WAS', careerGrade:'B', careerNote:'DROY 2020, injuries hampered ceiling' },
    { id:'20-12', name:'Cam Akers',         position:'RB',   actualPick:52,  actualRound:2, draftedBy:'LAR', careerGrade:'B', careerNote:'Key SB run, injuries after' },
    { id:'20-13', name:'Tua Tagovailoa',    position:'QB',   actualPick:5,   actualRound:1, draftedBy:'MIA', careerGrade:'B', careerNote:'Pro Bowl 2022, emerging franchise QB' },
    { id:'20-14', name:'Patrick Queen',     position:'LB',   actualPick:28,  actualRound:1, draftedBy:'BAL', careerGrade:'B', careerNote:'Starter-level ILB, Pro Bowl 2024' },
    { id:'20-15', name:'Jeff Okudah',       position:'CB',   actualPick:3,   actualRound:1, draftedBy:'DET', careerGrade:'D', careerNote:'Injuries ruined #3 pick investment' },
    { id:'20-16', name:'Jalen Reagor',      position:'WR',   actualPick:21,  actualRound:1, draftedBy:'PHI', careerGrade:'D', careerNote:'Major bust, limited impact' },
    { id:'20-17', name:'Mekhi Becton',      position:'OT',   actualPick:11,  actualRound:1, draftedBy:'NYJ', careerGrade:'D', careerNote:'Injuries and conditioning destroyed potential' },
    { id:'20-18', name:'Henry Ruggs III',   position:'WR',   actualPick:12,  actualRound:1, draftedBy:'LV',  careerGrade:'D', careerNote:'Tragic DUI incident ended career' },
  ],
  2021: [
    { id:'21-01', name:"Ja'Marr Chase",    position:'WR',   actualPick:5,   actualRound:1, draftedBy:'CIN', careerGrade:'S', careerNote:'3× Pro Bowl, ROTY 2021, Super Bowl WR, elite talent' },
    { id:'21-02', name:'Micah Parsons',    position:'EDGE', actualPick:12,  actualRound:1, draftedBy:'DAL', careerGrade:'S', careerNote:'3× All-Pro, 3× DPOY finalist, transformational defender' },
    { id:'21-03', name:'Penei Sewell',     position:'OT',   actualPick:7,   actualRound:1, draftedBy:'DET', careerGrade:'S', careerNote:'2× Pro Bowl, All-Pro, best OT in NFL' },
    { id:'21-04', name:'Patrick Surtain II',position:'CB',  actualPick:9,   actualRound:1, draftedBy:'DEN', careerGrade:'S', careerNote:'2× All-Pro, DPOY candidate, elite CB' },
    { id:'21-05', name:'Trevon Diggs',     position:'CB',   actualPick:51,  actualRound:2, draftedBy:'DAL', careerGrade:'A', careerNote:'All-Pro 2021 (11 INTs), Pro Bowl CB' },
    { id:'21-06', name:'Jevon Holland',    position:'S',    actualPick:36,  actualRound:2, draftedBy:'MIA', careerGrade:'A', careerNote:'Pro Bowl safety' },
    { id:'21-07', name:'Rashawn Slater',   position:'OT',   actualPick:13,  actualRound:1, draftedBy:'LAC', careerGrade:'A', careerNote:'2× Pro Bowl, elite LT' },
    { id:'21-08', name:'Travis Etienne Jr.',position:'RB',  actualPick:25,  actualRound:1, draftedBy:'JAX', careerGrade:'A', careerNote:'2× Pro Bowl, 1,600-yd season' },
    { id:'21-09', name:'DeVonta Smith',    position:'WR',   actualPick:10,  actualRound:1, draftedBy:'PHI', careerGrade:'A', careerNote:'2× Pro Bowl, 1,000-yd seasons, SB appearance' },
    { id:'21-10', name:'Jaylen Waddle',    position:'WR',   actualPick:6,   actualRound:1, draftedBy:'MIA', careerGrade:'A', careerNote:'2× Pro Bowl, fastest WR in class' },
    { id:'21-11', name:'Gregory Rousseau', position:'EDGE', actualPick:30,  actualRound:1, draftedBy:'BUF', careerGrade:'A', careerNote:'Double-digit sack seasons, key BUF defender' },
    { id:'21-12', name:'Trevor Lawrence',  position:'QB',   actualPick:1,   actualRound:1, draftedBy:'JAX', careerGrade:'A', careerNote:'Pro Bowl 2022, franchise QB of Jaguars' },
    { id:'21-13', name:'Asante Samuel Jr.',position:'CB',   actualPick:47,  actualRound:2, draftedBy:'LAC', careerGrade:'A', careerNote:'Emerging elite slot corner' },
    { id:'21-14', name:'Najee Harris',     position:'RB',   actualPick:24,  actualRound:1, draftedBy:'PIT', careerGrade:'B', careerNote:'Consistent workhorse RB' },
    { id:'21-15', name:'Javonte Williams', position:'RB',   actualPick:35,  actualRound:2, draftedBy:'DEN', careerGrade:'B', careerNote:'Elusive runner, 1,000+ yds before ACL' },
    { id:'21-16', name:'Kwity Paye',       position:'EDGE', actualPick:21,  actualRound:1, draftedBy:'IND', careerGrade:'B', careerNote:'Double-digit sacks, solid starter' },
    { id:'21-17', name:'Christian Darrisaw',position:'OT',  actualPick:23,  actualRound:1, draftedBy:'MIN', careerGrade:'A', careerNote:'Pro Bowl LT' },
    { id:'21-18', name:'Justin Fields',    position:'QB',   actualPick:11,  actualRound:1, draftedBy:'CHI', careerGrade:'B', careerNote:'Elite rusher, passing inconsistency' },
    { id:'21-19', name:'Kyle Pitts',       position:'TE',   actualPick:4,   actualRound:1, draftedBy:'ATL', careerGrade:'B', careerNote:'1,026 yds rookie year, injuries after' },
    { id:'21-20', name:'Zach Wilson',      position:'QB',   actualPick:2,   actualRound:1, draftedBy:'NYJ', careerGrade:'D', careerNote:'Major disappointment at #2 overall' },
    { id:'21-21', name:'Trey Lance',       position:'QB',   actualPick:3,   actualRound:1, draftedBy:'SF',  careerGrade:'D', careerNote:'Injuries derailed career before it started' },
    { id:'21-22', name:'Kadarius Toney',   position:'WR',   actualPick:20,  actualRound:1, draftedBy:'NYG', careerGrade:'D', careerNote:'Injuries and attitude issues' },
  ],
  2022: [
    { id:'22-01', name:'Aidan Hutchinson',   position:'EDGE', actualPick:2,   actualRound:1, draftedBy:'DET', careerGrade:'S', careerNote:'3× Pro Bowl, elite pass rusher, face of DET rebuild' },
    { id:'22-02', name:'Sauce Gardner',      position:'CB',   actualPick:4,   actualRound:1, draftedBy:'NYJ', careerGrade:'S', careerNote:'3× All-Pro, DROY 2022, premier shutdown corner' },
    { id:'22-03', name:'Garrett Wilson',     position:'WR',   actualPick:10,  actualRound:1, draftedBy:'NYJ', careerGrade:'S', careerNote:'ROTY 2022, 3× Pro Bowl, elite route runner' },
    { id:'22-04', name:'Kerby Joseph',       position:'S',    actualPick:97,  actualRound:3, draftedBy:'DET', careerGrade:'A', careerNote:'11 INTs in 2 seasons, elite ballhawk' },
    { id:'22-05', name:'Christian Harris',   position:'LB',   actualPick:75,  actualRound:3, draftedBy:'HOU', careerGrade:'A', careerNote:'Pro Bowl 2024, elite ILB' },
    { id:'22-06', name:'Drake London',       position:'WR',   actualPick:8,   actualRound:1, draftedBy:'ATL', careerGrade:'A', careerNote:'Pro Bowl 2024, emerging WR1' },
    { id:'22-07', name:'Breece Hall',        position:'RB',   actualPick:36,  actualRound:2, draftedBy:'NYJ', careerGrade:'A', careerNote:'1,500-yd season, electric playmaker' },
    { id:'22-08', name:'Kayvon Thibodeaux', position:'EDGE', actualPick:5,   actualRound:1, draftedBy:'NYG', careerGrade:'B', careerNote:'Emerging pass rusher, double-digit sacks' },
    { id:'22-09', name:'Jordan Davis',       position:'DT',   actualPick:13,  actualRound:1, draftedBy:'PHI', careerGrade:'B', careerNote:'Elite run-stopper, SB appearance' },
    { id:'22-10', name:'Charles Cross',      position:'OT',   actualPick:9,   actualRound:1, draftedBy:'SEA', careerGrade:'A', careerNote:'Pro Bowl LT 2023' },
    { id:'22-11', name:'Christian Watson',   position:'WR',   actualPick:34,  actualRound:2, draftedBy:'GB',  careerGrade:'B', careerNote:'10 TDs rookie year, solid WR2' },
    { id:'22-12', name:'Jameson Williams',   position:'WR',   actualPick:12,  actualRound:1, draftedBy:'DET', careerGrade:'B', careerNote:'Speed threat, suspension set back' },
    { id:'22-13', name:'Travon Walker',      position:'EDGE', actualPick:1,   actualRound:1, draftedBy:'JAX', careerGrade:'C', careerNote:'Below expectations for #1 pick' },
    { id:'22-14', name:'Ikem Ekwonu',        position:'OT',   actualPick:6,   actualRound:1, draftedBy:'CAR', careerGrade:'B', careerNote:'Starter-level LT' },
    { id:'22-15', name:'Lewis Cine',         position:'S',    actualPick:32,  actualRound:1, draftedBy:'MIN', careerGrade:'D', careerNote:'Catastrophic leg injury, career derailed' },
    { id:'22-16', name:'Kenyon Green',       position:'OG',   actualPick:15,  actualRound:1, draftedBy:'HOU', careerGrade:'D', careerNote:'Disappointing start to career' },
  ],
  2023: [
    { id:'23-01', name:'CJ Stroud',         position:'QB',   actualPick:2,   actualRound:1, draftedBy:'HOU', careerGrade:'S', careerNote:'ROTY 2023, Pro Bowl, led HOU to playoffs year 1' },
    { id:'23-02', name:'Jalen Carter',      position:'DT',   actualPick:9,   actualRound:1, draftedBy:'PHI', careerGrade:'S', careerNote:'2× Pro Bowl, dominant interior presence' },
    { id:'23-03', name:'Will Anderson Jr.', position:'EDGE', actualPick:3,   actualRound:1, draftedBy:'HOU', careerGrade:'S', careerNote:'17.5 sacks in 2024, elite pass rusher' },
    { id:'23-04', name:'Puka Nacua',        position:'WR',   actualPick:177, actualRound:5, draftedBy:'LAR', careerGrade:'A', careerNote:'All-time rookie record 105 catches, 1,486 yds' },
    { id:'23-05', name:'Devon Achane',      position:'RB',   actualPick:84,  actualRound:3, draftedBy:'MIA', careerGrade:'S', careerNote:'Pro Bowl, fastest RB in NFL' },
    { id:'23-06', name:'Jahmyr Gibbs',      position:'RB',   actualPick:12,  actualRound:1, draftedBy:'DET', careerGrade:'S', careerNote:'Pro Bowl 2024, elite dual-threat back' },
    { id:'23-07', name:'Jordan Addison',    position:'WR',   actualPick:23,  actualRound:1, draftedBy:'MIN', careerGrade:'A', careerNote:'1,000-yd season year 2, 10 TDs' },
    { id:'23-08', name:'Nathaniel Dell',    position:'WR',   actualPick:69,  actualRound:3, draftedBy:'HOU', careerGrade:'A', careerNote:'1,100-yd season, key piece of HOU offense' },
    { id:'23-09', name:'Zay Flowers',       position:'WR',   actualPick:22,  actualRound:1, draftedBy:'BAL', careerGrade:'A', careerNote:'Key SB run, 858 yds + TDs' },
    { id:'23-10', name:'Bijan Robinson',    position:'RB',   actualPick:8,   actualRound:1, draftedBy:'ATL', careerGrade:'A', careerNote:'1,000-yd season year 2, Pro Bowl' },
    { id:'23-11', name:'Brian Branch',      position:'S',    actualPick:45,  actualRound:2, draftedBy:'DET', careerGrade:'A', careerNote:'Pro Bowl safety 2024' },
    { id:'23-12', name:'Joey Porter Jr.',   position:'CB',   actualPick:32,  actualRound:1, draftedBy:'PIT', careerGrade:'A', careerNote:'Pro Bowl CB 2024' },
    { id:'23-13', name:'Peter Skoronski',   position:'OT',   actualPick:11,  actualRound:1, draftedBy:'TEN', careerGrade:'A', careerNote:'Pro Bowl-caliber OG/OT' },
    { id:'23-14', name:'Darnell Wright',    position:'OT',   actualPick:10,  actualRound:1, draftedBy:'CHI', careerGrade:'A', careerNote:'Strong RT, anchor of CHI line' },
    { id:'23-15', name:'Bryce Young',       position:'QB',   actualPick:1,   actualRound:1, draftedBy:'CAR', careerGrade:'C', careerNote:'Struggled with poor supporting cast' },
    { id:'23-16', name:'Anthony Richardson',position:'QB',   actualPick:4,   actualRound:1, draftedBy:'IND', careerGrade:'B', careerNote:'Electric athleticism, injuries + accuracy questions' },
    { id:'23-17', name:'Lukas Van Ness',    position:'EDGE', actualPick:13,  actualRound:1, draftedBy:'GB',  careerGrade:'C', careerNote:'Still developing' },
    { id:'23-18', name:'Tyree Wilson',      position:'EDGE', actualPick:7,   actualRound:1, draftedBy:'LV',  careerGrade:'C', careerNote:'Below expectations through 2 years' },
  ],
  2024: [
    { id:'24-01', name:'Jayden Daniels',      position:'QB',  actualPick:2,   actualRound:1, draftedBy:'WAS', careerGrade:'S', careerNote:'ROTY 2024, NFC Championship, instant franchise QB' },
    { id:'24-02', name:'Brock Bowers',        position:'TE',  actualPick:13,  actualRound:1, draftedBy:'LV',  careerGrade:'S', careerNote:'All-time TE rookie record (112 rec, 1,194 yds)' },
    { id:'24-03', name:'Quinyon Mitchell',    position:'CB',  actualPick:22,  actualRound:1, draftedBy:'PHI', careerGrade:'S', careerNote:'Best rookie CB in years, 0 TDs allowed, SB run' },
    { id:'24-04', name:'Joe Alt',             position:'OT',  actualPick:5,   actualRound:1, draftedBy:'LAC', careerGrade:'S', careerNote:'Immediate All-Pro caliber, best rookie OT in years' },
    { id:'24-05', name:'Brian Thomas Jr.',    position:'WR',  actualPick:23,  actualRound:1, draftedBy:'JAX', careerGrade:'A', careerNote:'1,282-yd rookie season, elite deep threat' },
    { id:'24-06', name:'Ladd McConkey',       position:'WR',  actualPick:34,  actualRound:2, draftedBy:'LAC', careerGrade:'A', careerNote:'1,000-yd rookie season, elite slot' },
    { id:'24-07', name:'Xavier Worthy',       position:'WR',  actualPick:28,  actualRound:1, draftedBy:'KC',  careerGrade:'A', careerNote:'6 TDs rookie, SB champ, 4.21 speed' },
    { id:'24-08', name:'Jared Verse',         position:'EDGE',actualPick:19,  actualRound:1, draftedBy:'LAR', careerGrade:'A', careerNote:'8 sacks rookie year, immediate impact' },
    { id:'24-09', name:'Terrion Arnold',      position:'CB',  actualPick:24,  actualRound:1, draftedBy:'DET', careerGrade:'A', careerNote:'6 INTs rookie year, elite ballhawk' },
    { id:'24-10', name:'Cooper DeJean',       position:'S',   actualPick:40,  actualRound:2, draftedBy:'PHI', careerGrade:'A', careerNote:'Versatile star, SB run, key PHI defender' },
    { id:'24-11', name:'Payton Wilson',       position:'LB',  actualPick:55,  actualRound:2, draftedBy:'PIT', careerGrade:'A', careerNote:'Instant starter, tackling machine' },
    { id:'24-12', name:'Marvin Harrison Jr.', position:'WR',  actualPick:4,   actualRound:1, draftedBy:'ARI', careerGrade:'A', careerNote:'879 yds rookie year, generational talent developing' },
    { id:'24-13', name:'Olu Fashanu',         position:'OT',  actualPick:11,  actualRound:1, draftedBy:'NYJ', careerGrade:'A', careerNote:'Strong starter-level LT' },
    { id:'24-14', name:'Caleb Williams',      position:'QB',  actualPick:1,   actualRound:1, draftedBy:'CHI', careerGrade:'B', careerNote:'Promising rookie, 3,541 yds, showed flashes' },
    { id:'24-15', name:'Rome Odunze',         position:'WR',  actualPick:9,   actualRound:1, draftedBy:'CHI', careerGrade:'B', careerNote:'746 yds rookie, developing WR1' },
    { id:'24-16', name:'Drake Maye',          position:'QB',  actualPick:3,   actualRound:1, draftedBy:'NE',  careerGrade:'A', careerNote:'Promising in limited action, future franchise QB' },
    { id:'24-17', name:'Jackson Powers-Johnson',position:'C', actualPick:36,  actualRound:2, draftedBy:'GB',  careerGrade:'A', careerNote:'Immediate starter, strong rookie season' },
  ],
  2025: [
    { id:'25-01', name:'Travis Hunter',      position:'CB/WR',actualPick:2,  actualRound:1, draftedBy:'JAX', careerGrade:'S', careerNote:'Heisman winner, unique 2-way talent — generational prospect' },
    { id:'25-02', name:'Cam Ward',           position:'QB',   actualPick:1,  actualRound:1,  draftedBy:'TEN', careerGrade:'B', careerNote:'#1 overall, projected franchise QB' },
    { id:'25-03', name:'Abdul Carter',       position:'EDGE', actualPick:3,  actualRound:1,  draftedBy:'NYG', careerGrade:'A', careerNote:'Premier pass-rush prospect' },
    { id:'25-04', name:'Will Campbell',      position:'OT',   actualPick:4,  actualRound:1,  draftedBy:'NE',  careerGrade:'A', careerNote:'Elite OT prospect' },
    { id:'25-05', name:'Mason Graham',       position:'DT',   actualPick:6,  actualRound:1,  draftedBy:'CLE', careerGrade:'A', careerNote:'Best DT prospect in years' },
    { id:'25-06', name:'Ashton Jeanty',      position:'RB',   actualPick:9,  actualRound:1,  draftedBy:'LV',  careerGrade:'A', careerNote:'Heisman runner-up, 2,601-yd season' },
    { id:'25-07', name:'Tetairoa McMillan',  position:'WR',   actualPick:8,  actualRound:1,  draftedBy:'CAR', careerGrade:'A', careerNote:'Massive WR1, elite red-zone target' },
    { id:'25-08', name:'Tyler Warren',       position:'TE',   actualPick:16, actualRound:1,  draftedBy:'IND', careerGrade:'A', careerNote:'115 catches at Penn State, elite TE' },
    { id:'25-09', name:'Omarion Hampton',    position:'RB',   actualPick:22, actualRound:1,  draftedBy:'LAC', careerGrade:'A', careerNote:'Best RB prospect, powered UNC offense' },
    { id:'25-10', name:'Mykel Williams',     position:'EDGE', actualPick:7,  actualRound:1,  draftedBy:'SF',  careerGrade:'A', careerNote:'High-upside edge rusher' },
    { id:'25-11', name:'Colston Loveland',   position:'TE',   actualPick:10, actualRound:1,  draftedBy:'CHI', careerGrade:'A', careerNote:'Athletic TE, top-10 value' },
    { id:'25-12', name:'Malaki Starks',      position:'S',    actualPick:27, actualRound:1,  draftedBy:'BAL', careerGrade:'A', careerNote:'Rangy, ballhawking safety' },
    { id:'25-13', name:'Kelvin Banks Jr.',   position:'OT',   actualPick:17, actualRound:1,  draftedBy:'HOU', careerGrade:'A', careerNote:'LT of future for HOU' },
    { id:'25-14', name:'Mike Green',         position:'EDGE', actualPick:51, actualRound:2,  draftedBy:'LAR', careerGrade:'A', careerNote:'Led NCAA in sacks, elite rusher' },
    { id:'25-15', name:'Armand Membou',      position:'OT',   actualPick:14, actualRound:1,  draftedBy:'KC',  careerGrade:'A', careerNote:'Athletic OT, SB team investment' },
    { id:'25-16', name:'Matthew Golden',     position:'WR',   actualPick:23, actualRound:1,  draftedBy:'GB',  careerGrade:'B', careerNote:'Speed WR, big-play ability' },
    { id:'25-17', name:'Shedeur Sanders',    position:'QB',   actualPick:144,actualRound:5,  draftedBy:'CLE', careerGrade:'C', careerNote:'Unexpected slide, upside potential' },
    { id:'25-18', name:'Nick Emmanwori',     position:'S',    actualPick:37, actualRound:2,  draftedBy:'SEA', careerGrade:'B', careerNote:'SEC Defensive Player of Year' },
    { id:'25-19', name:'Jahdae Barron',      position:'CB',   actualPick:29, actualRound:1,  draftedBy:'GB',  careerGrade:'B', careerNote:'Versatile CB/S prospect' },
  ],
};