import type { TeamInfo } from './types';

export const TEAM_DATA: Record<number, Record<string, TeamInfo>> = {
  2016: {
    ARI:{ n:['RB','CB','EDGE'],    s:['Carson Palmer','Larry Fitzgerald','David Johnson'],     w:'13-3' },
    ATL:{ n:['CB','EDGE','WR'],    s:['Matt Ryan','Julio Jones','Devonta Freeman'],             w:'8-8' },
    BAL:{ n:['OT','WR','CB'],      s:['Joe Flacco','Justin Tucker','Terrell Suggs'],            w:'5-11' },
    BUF:{ n:['WR','CB','QB'],      s:['Tyrod Taylor','LeSean McCoy','Stephon Gilmore'],         w:'8-8' },
    CAR:{ n:['WR','CB','S'],       s:['Cam Newton','Greg Olsen','Luke Kuechly'],                w:'15-1' },
    CHI:{ n:['QB','WR','OT'],      s:['Alshon Jeffery','Matt Forte'],                          w:'6-10' },
    CIN:{ n:['OT','CB','WR'],      s:['A.J. Green','Andy Dalton','Tyler Eifert'],              w:'12-4' },
    CLE:{ n:['QB','WR','CB'],      s:['Joe Thomas'],                                           w:'3-13' },
    DAL:{ n:['RB','WR','CB'],      s:['Dez Bryant','Jason Witten','Travis Frederick'],         w:'4-12' },
    DEN:{ n:['QB','WR','OT'],      s:['Von Miller','Emmanuel Sanders','Aqib Talib'],           w:'12-4' },
    DET:{ n:['WR','RB','EDGE'],    s:['Matthew Stafford','Golden Tate'],                       w:'7-9' },
    GB: { n:['CB','EDGE','RB'],    s:['Aaron Rodgers','Jordy Nelson','Randall Cobb'],          w:'10-6' },
    HOU:{ n:['WR','OT','EDGE'],    s:['J.J. Watt','DeAndre Hopkins','Lamar Miller'],           w:'9-7' },
    IND:{ n:['OT','CB','EDGE'],    s:['Andrew Luck','T.Y. Hilton','Frank Gore'],               w:'8-8' },
    JAX:{ n:['CB','WR','QB'],      s:['Allen Robinson','Malik Jackson'],                       w:'5-11' },
    KC: { n:['WR','CB','OT'],      s:['Alex Smith','Travis Kelce','Jeremy Maclin'],            w:'11-5' },
    LAR:{ n:['QB','WR','OT'],      s:['Todd Gurley','Robert Quinn'],                           w:'7-9' },
    MIA:{ n:['OT','WR','CB'],      s:['Ryan Tannehill','Jarvis Landry','Ndamukong Suh'],       w:'6-10' },
    MIN:{ n:['QB','WR','RB'],      s:['Adrian Peterson','Stefon Diggs','Kyle Rudolph'],        w:'11-5' },
    NE: { n:['EDGE','CB','WR'],    s:['Tom Brady','Rob Gronkowski','Malcolm Butler'],          w:'12-4' },
    NO: { n:['WR','DT','LB'],      s:['Drew Brees','Brandin Cooks','Mark Ingram'],             w:'7-9' },
    NYG:{ n:['CB','EDGE','WR'],    s:['Eli Manning','Odell Beckham Jr.','Victor Cruz'],        w:'6-10' },
    NYJ:{ n:['QB','WR','CB'],      s:['Brandon Marshall','Darrelle Revis'],                    w:'10-6' },
    OAK:{ n:['S','CB','WR'],       s:['Derek Carr','Amari Cooper','Khalil Mack'],              w:'7-9' },
    PHI:{ n:['QB','WR','CB'],      s:['Zach Ertz','Jordan Matthews','Fletcher Cox'],           w:'7-9' },
    PIT:{ n:['CB','OT','S'],       s:["Ben Roethlisberger","Antonio Brown","Le'Veon Bell"],    w:'10-6' },
    SD: { n:['EDGE','CB','OT'],    s:['Philip Rivers','Keenan Allen','Antonio Gates'],         w:'4-12' },
    SEA:{ n:['RB','EDGE','DT'],    s:['Russell Wilson','Richard Sherman','Earl Thomas'],       w:'10-6' },
    SF: { n:['QB','WR','OT'],      s:['NaVorro Bowman','Carlos Hyde'],                         w:'5-11' },
    TB: { n:['WR','CB','OT'],      s:['Jameis Winston','Mike Evans','Gerald McCoy'],           w:'6-10' },
    TEN:{ n:['WR','OT','EDGE'],    s:['Marcus Mariota','Delanie Walker'],                      w:'3-13' },
    WAS:{ n:['RB','CB','OT'],      s:['Kirk Cousins','DeSean Jackson','Jordan Reed'],          w:'9-7' },
  },
  2017: {
    ARI:{ n:['CB','EDGE','OT'],    s:['Carson Palmer','Larry Fitzgerald','David Johnson'],     w:'7-8-1' },
    ATL:{ n:['CB','DT','OT'],      s:['Matt Ryan','Julio Jones','Devonta Freeman'],            w:'11-5' },
    BAL:{ n:['WR','CB','OT'],      s:['Joe Flacco','Justin Tucker','Terrell Suggs'],           w:'8-8' },
    BUF:{ n:['WR','CB','QB'],      s:['Tyrod Taylor','LeSean McCoy','Stephon Gilmore'],        w:'7-9' },
    CAR:{ n:['WR','RB','CB'],      s:['Cam Newton','Greg Olsen','Luke Kuechly'],               w:'6-10' },
    CHI:{ n:['QB','WR','OT'],      s:['Kevin White'],                                          w:'3-13' },
    CIN:{ n:['WR','OT','EDGE'],    s:['A.J. Green','Andy Dalton','Joe Mixon'],                 w:'6-9-1' },
    CLE:{ n:['QB','WR','OT'],      s:['Joe Thomas'],                                           w:'1-15' },
    DAL:{ n:['CB','DT','EDGE'],    s:['Dak Prescott','Ezekiel Elliott','Dez Bryant'],          w:'13-3' },
    DEN:{ n:['QB','WR','OT'],      s:['Von Miller','Emmanuel Sanders','Aqib Talib'],           w:'9-7' },
    DET:{ n:['WR','CB','EDGE'],    s:['Matthew Stafford','Golden Tate','Darius Slay'],        w:'9-7' },
    GB: { n:['CB','EDGE','RB'],    s:['Aaron Rodgers','Jordy Nelson','Randall Cobb'],          w:'10-6' },
    HOU:{ n:['WR','OT','LB'],      s:['J.J. Watt','DeAndre Hopkins','Lamar Miller'],           w:'9-7' },
    IND:{ n:['OT','EDGE','CB'],    s:['Andrew Luck','T.Y. Hilton','Frank Gore'],               w:'8-8' },
    JAX:{ n:['RB','WR','OT'],      s:['Jalen Ramsey','Telvin Smith','Malik Jackson'],         w:'3-13' },
    KC: { n:['QB','CB','EDGE'],    s:['Alex Smith','Travis Kelce','Tyreek Hill'],              w:'12-4' },
    LAC:{ n:['EDGE','S','WR'],     s:['Philip Rivers','Keenan Allen','Joey Bosa'],            w:'5-11' },
    LAR:{ n:['QB','WR','CB'],      s:['Todd Gurley','Robert Quinn'],                           w:'4-12' },
    MIA:{ n:['OT','WR','CB'],      s:['Ryan Tannehill','Jarvis Landry','Ndamukong Suh'],      w:'10-6' },
    MIN:{ n:['QB','RB','CB'],      s:['Stefon Diggs','Adam Thielen','Kyle Rudolph'],           w:'8-8' },
    NE: { n:['EDGE','CB','WR'],    s:['Tom Brady','Rob Gronkowski','Malcolm Butler'],          w:'14-2' },
    NO: { n:['OT','CB','EDGE'],    s:['Drew Brees','Michael Thomas','Mark Ingram'],            w:'7-9' },
    NYG:{ n:['EDGE','OT','CB'],    s:['Eli Manning','Odell Beckham Jr.'],                      w:'11-5' },
    NYJ:{ n:['QB','WR','CB'],      s:['Brandon Marshall','Eric Decker'],                       w:'5-11' },
    OAK:{ n:['CB','S','OT'],       s:['Derek Carr','Amari Cooper','Khalil Mack'],              w:'12-4' },
    PHI:{ n:['WR','CB','EDGE'],    s:['Carson Wentz','Zach Ertz','Jordan Matthews'],           w:'7-9' },
    PIT:{ n:['CB','OT','DE'],      s:["Ben Roethlisberger","Antonio Brown","Le'Veon Bell"],    w:'11-5' },
    SEA:{ n:['RB','EDGE','DT'],    s:['Russell Wilson','Richard Sherman','Earl Thomas'],       w:'10-6' },
    SF: { n:['QB','WR','OT'],      s:['Carlos Hyde','NaVorro Bowman'],                         w:'2-14' },
    TB: { n:['WR','CB','OT'],      s:['Jameis Winston','Mike Evans','Gerald McCoy'],           w:'9-7' },
    TEN:{ n:['WR','OT','CB'],      s:['Marcus Mariota','Delanie Walker','DeMarco Murray'],     w:'9-7' },
    WAS:{ n:['WR','CB','OT'],      s:['Kirk Cousins','Jordan Reed','DeSean Jackson'],          w:'8-7-1' },
  },
  2018: {
    ARI:{ n:['QB','WR','OT'],      s:['Larry Fitzgerald','Patrick Peterson','David Johnson'],  w:'8-8' },
    ATL:{ n:['CB','OT','DT'],      s:['Matt Ryan','Julio Jones','Devonta Freeman'],            w:'10-6' },
    BAL:{ n:['WR','CB','EDGE'],    s:['Joe Flacco','Justin Tucker','Terrell Suggs'],           w:'9-7' },
    BUF:{ n:['QB','WR','CB'],      s:['Shady McCoy','Jordan Matthews'],                        w:'9-7' },
    CAR:{ n:['WR','CB','EDGE'],    s:['Cam Newton','Greg Olsen','Luke Kuechly','CMC'],         w:'11-5' },
    CHI:{ n:['QB','WR','EDGE'],    s:['Tarik Cohen','Jordan Howard'],                          w:'5-11' },
    CIN:{ n:['OT','WR','CB'],      s:['A.J. Green','Andy Dalton','Joe Mixon'],                 w:'7-9' },
    CLE:{ n:['QB','WR','CB'],      s:['Joe Thomas','Josh Gordon'],                             w:'0-16' },
    DAL:{ n:['WR','CB','OT'],      s:['Dak Prescott','Ezekiel Elliott','Dez Bryant'],          w:'9-7' },
    DEN:{ n:['QB','WR','OT'],      s:['Von Miller','Emmanuel Sanders','Aqib Talib'],           w:'5-11' },
    DET:{ n:['WR','CB','EDGE'],    s:['Matthew Stafford','Marvin Jones','Darius Slay'],       w:'9-7' },
    GB: { n:['EDGE','CB','RB'],    s:['Aaron Rodgers','Davante Adams','Clay Matthews'],        w:'7-9' },
    HOU:{ n:['WR','OT','LB'],      s:['Deshaun Watson','DeAndre Hopkins','J.J. Watt'],         w:'4-12' },
    IND:{ n:['OT','EDGE','CB'],    s:['Andrew Luck','T.Y. Hilton','Frank Gore'],               w:'4-12' },
    JAX:{ n:['QB','WR','OT'],      s:['Jalen Ramsey','Calais Campbell','Leonard Fournette'],  w:'10-6' },
    KC: { n:['EDGE','CB','WR'],    s:['Patrick Mahomes','Travis Kelce','Tyreek Hill'],         w:'10-6' },
    LAC:{ n:['OT','S','CB'],       s:['Philip Rivers','Keenan Allen','Joey Bosa'],            w:'8-8' },
    LAR:{ n:['CB','EDGE','OT'],    s:['Todd Gurley','Aaron Donald','Cooper Kupp'],             w:'11-5' },
    MIA:{ n:['WR','QB','CB'],      s:['Ryan Tannehill','Laremy Tunsil'],                       w:'6-10' },
    MIN:{ n:['QB','RB','OT'],      s:['Stefon Diggs','Adam Thielen','Kirk Cousins'],           w:'13-3' },
    NE: { n:['WR','EDGE','CB'],    s:['Tom Brady','Rob Gronkowski','Julian Edelman'],          w:'13-3' },
    NO: { n:['OT','CB','EDGE'],    s:['Drew Brees','Michael Thomas','Alvin Kamara'],           w:'11-5' },
    NYG:{ n:['EDGE','OT','RB'],    s:['Eli Manning','Odell Beckham Jr.'],                      w:'3-13' },
    NYJ:{ n:['QB','WR','CB'],      s:['Quincy Enunwa'],                                        w:'5-11' },
    OAK:{ n:['EDGE','CB','OT'],    s:['Derek Carr','Amari Cooper'],                            w:'6-10' },
    PHI:{ n:['WR','CB','EDGE'],    s:['Carson Wentz','Zach Ertz','Alshon Jeffery'],            w:'13-3' },
    PIT:{ n:['CB','OT','EDGE'],    s:["Ben Roethlisberger","Antonio Brown","Le'Veon Bell"],    w:'13-3' },
    SEA:{ n:['CB','RB','EDGE'],    s:['Russell Wilson','Tyler Lockett','Bobby Wagner'],        w:'9-7' },
    SF: { n:['WR','CB','EDGE'],    s:['Jimmy Garoppolo','George Kittle','Richard Sherman'],    w:'6-10' },
    TB: { n:['WR','CB','OT'],      s:['Jameis Winston','Mike Evans','Chris Godwin'],           w:'5-11' },
    TEN:{ n:['WR','OT','CB'],      s:['Marcus Mariota','Delanie Walker','Derrick Henry'],      w:'9-7' },
    WAS:{ n:['QB','WR','CB'],      s:['Jordan Reed','Josh Doctson','Josh Norman'],             w:'7-9' },
  },
  2019: {
    ARI:{ n:['QB','WR','OT'],      s:['Larry Fitzgerald','Patrick Peterson','David Johnson'],  w:'3-13' },
    ATL:{ n:['CB','OT','EDGE'],    s:['Matt Ryan','Julio Jones','Calvin Ridley'],              w:'7-9' },
    BAL:{ n:['WR','CB','OT'],      s:['Lamar Jackson','Mark Andrews','Justin Tucker'],         w:'10-6' },
    BUF:{ n:['WR','CB','OT'],      s:['Josh Allen','LeSean McCoy'],                            w:'6-10' },
    CAR:{ n:['WR','CB','EDGE'],    s:['Cam Newton','Greg Olsen','Christian McCaffrey'],        w:'7-9' },
    CHI:{ n:['WR','EDGE','CB'],    s:['Khalil Mack','Allen Robinson','Mitchell Trubisky'],     w:'12-4' },
    CIN:{ n:['OT','EDGE','CB'],    s:['A.J. Green','Andy Dalton','Joe Mixon'],                 w:'6-10' },
    CLE:{ n:['WR','CB','OT'],      s:['Baker Mayfield','Jarvis Landry','Odell Beckham'],       w:'7-8-1' },
    DAL:{ n:['CB','EDGE','OT'],    s:['Dak Prescott','Ezekiel Elliott','Amari Cooper'],        w:'10-6' },
    DEN:{ n:['QB','WR','OT'],      s:['Von Miller','Emmanuel Sanders'],                        w:'6-10' },
    DET:{ n:['EDGE','OT','LB'],    s:['Matthew Stafford','Kenny Golladay','Darius Slay'],     w:'6-10' },
    GB: { n:['WR','RB','CB'],      s:['Aaron Rodgers','Davante Adams',"Za'Darius Smith"],     w:'6-9-1' },
    HOU:{ n:['WR','OT','CB'],      s:['Deshaun Watson','DeAndre Hopkins','J.J. Watt'],         w:'11-5' },
    IND:{ n:['EDGE','CB','WR'],    s:['Andrew Luck','T.Y. Hilton','Quenton Nelson'],           w:'10-6' },
    JAX:{ n:['QB','WR','OT'],      s:['Jalen Ramsey','Leonard Fournette'],                     w:'5-11' },
    KC: { n:['CB','EDGE','OT'],    s:['Patrick Mahomes','Travis Kelce','Tyreek Hill'],         w:'12-4' },
    LAC:{ n:['S','OT','WR'],       s:['Philip Rivers','Keenan Allen','Joey Bosa'],            w:'12-4' },
    LAR:{ n:['CB','S','EDGE'],     s:['Todd Gurley','Aaron Donald','Cooper Kupp'],             w:'13-3' },
    MIA:{ n:['QB','WR','OT'],      s:['Ryan Fitzpatrick','Danny Amendola'],                    w:'7-9' },
    MIN:{ n:['CB','EDGE','OT'],    s:['Kirk Cousins','Adam Thielen','Stefon Diggs'],           w:'8-7-1' },
    NE: { n:['WR','EDGE','CB'],    s:['Tom Brady','Julian Edelman'],                           w:'11-5' },
    NO: { n:['CB','EDGE','OT'],    s:['Drew Brees','Michael Thomas','Alvin Kamara'],           w:'13-3' },
    NYG:{ n:['QB','WR','EDGE'],    s:['Saquon Barkley'],                                       w:'5-11' },
    NYJ:{ n:['QB','WR','OT'],      s:['Sam Darnold'],                                          w:'4-12' },
    OAK:{ n:['WR','CB','OT'],      s:['Derek Carr','Jordy Nelson','Maxx Crosby'],              w:'4-12' },
    PHI:{ n:['CB','WR','OT'],      s:['Carson Wentz','Zach Ertz','Alshon Jeffery'],            w:'9-7' },
    PIT:{ n:['WR','RB','CB'],      s:["Ben Roethlisberger","JuJu Smith-Schuster","TJ Watt"],   w:'9-6-1' },
    SEA:{ n:['CB','WR','EDGE'],    s:['Russell Wilson','Tyler Lockett','Bobby Wagner'],        w:'10-6' },
    SF: { n:['WR','CB','OT'],      s:['Jimmy Garoppolo','George Kittle','Dee Ford'],           w:'4-12' },
    TB: { n:['CB','EDGE','OT'],    s:['Jameis Winston','Mike Evans','Chris Godwin'],           w:'5-11' },
    TEN:{ n:['WR','OT','CB'],      s:['Marcus Mariota','Derrick Henry','Delanie Walker'],      w:'9-7' },
    WAS:{ n:['QB','WR','CB'],      s:['Terry McLaurin','Jordan Reed'],                         w:'7-9' },
  },
  2020: {
    ARI:{ n:['OT','CB','WR'],      s:['Kyler Murray','DeAndre Hopkins','Patrick Peterson'],    w:'5-10-1' },
    ATL:{ n:['CB','OT','EDGE'],    s:['Matt Ryan','Julio Jones','Calvin Ridley'],              w:'7-9' },
    BAL:{ n:['WR','CB','DT'],      s:['Lamar Jackson','Mark Andrews','Marcus Peters'],         w:'14-2' },
    BUF:{ n:['WR','EDGE','CB'],    s:['Josh Allen','Stefon Diggs','Tre White'],                w:'10-6' },
    CAR:{ n:['QB','WR','CB'],      s:['Christian McCaffrey','DJ Moore','Brian Burns'],          w:'5-11' },
    CHI:{ n:['WR','OT','QB'],      s:['Khalil Mack','Allen Robinson','Mitchell Trubisky'],     w:'8-8' },
    CIN:{ n:['QB','OT','WR'],      s:['A.J. Green','Joe Mixon'],                               w:'2-14' },
    CLE:{ n:['CB','OT','EDGE'],    s:['Baker Mayfield','Jarvis Landry','Odell Beckham'],       w:'6-10' },
    DAL:{ n:['CB','OT','EDGE'],    s:['Dak Prescott','Ezekiel Elliott','CeeDee Lamb'],         w:'8-8' },
    DEN:{ n:['QB','WR','OT'],      s:['Von Miller','Courtland Sutton'],                        w:'7-9' },
    DET:{ n:['EDGE','OT','CB'],    s:['Matthew Stafford','Kenny Golladay','Darius Slay'],     w:'3-12-1' },
    GB: { n:['WR','RB','CB'],      s:['Aaron Rodgers','Davante Adams',"Za'Darius Smith"],     w:'13-3' },
    HOU:{ n:['WR','OT','CB'],      s:['Deshaun Watson','J.J. Watt'],                          w:'10-6' },
    IND:{ n:['QB','WR','CB'],      s:['Quenton Nelson','T.Y. Hilton','Darius Leonard'],        w:'7-9' },
    JAX:{ n:['QB','WR','OT'],      s:['Josh Allen DE'],                                        w:'6-10' },
    KC: { n:['EDGE','OT','CB'],    s:['Patrick Mahomes','Travis Kelce','Tyreek Hill'],         w:'12-4' },
    LAC:{ n:['QB','WR','OT'],      s:['Keenan Allen','Joey Bosa'],                             w:'5-11' },
    LAR:{ n:['CB','WR','OT'],      s:['Aaron Donald','Cooper Kupp','Jared Goff'],             w:'9-7' },
    LV: { n:['WR','CB','OT'],      s:['Derek Carr','Josh Jacobs','Maxx Crosby'],               w:'7-9' },
    MIA:{ n:['QB','WR','OT'],      s:['DeVante Parker','Laremy Tunsil'],                       w:'5-11' },
    MIN:{ n:['WR','CB','EDGE'],    s:['Kirk Cousins','Dalvin Cook','Adam Thielen'],            w:'10-6' },
    NE: { n:['QB','WR','OT'],      s:['Julian Edelman','Stephon Gilmore'],                     w:'12-4' },
    NO: { n:['CB','EDGE','WR'],    s:['Drew Brees','Michael Thomas','Alvin Kamara'],           w:'13-3' },
    NYG:{ n:['OT','WR','CB'],      s:['Saquon Barkley','Daniel Jones'],                        w:'4-12' },
    NYJ:{ n:['QB','OT','CB'],      s:['Sam Darnold','Jamison Crowder'],                        w:'7-9' },
    PHI:{ n:['WR','CB','EDGE'],    s:['Carson Wentz','Zach Ertz','Alshon Jeffery'],            w:'9-7' },
    PIT:{ n:['OT','WR','CB'],      s:["Ben Roethlisberger","JuJu Smith-Schuster","TJ Watt"],   w:'8-8' },
    SEA:{ n:['EDGE','OT','CB'],    s:['Russell Wilson','Tyler Lockett','Bobby Wagner'],        w:'11-5' },
    SF: { n:['WR','CB','EDGE'],    s:['Jimmy Garoppolo','George Kittle','Deebo Samuel'],       w:'13-3' },
    TB: { n:['QB','CB','OT'],      s:['Mike Evans','Chris Godwin','Shaq Barrett'],             w:'7-9' },
    TEN:{ n:['WR','OT','CB'],      s:['Ryan Tannehill','Derrick Henry','AJ Brown'],            w:'9-7' },
    WAS:{ n:['QB','CB','OT'],      s:['Terry McLaurin','Chase Young','Ron Rivera HC'],         w:'3-13' },
  },
  2021: {
    ARI:{ n:['WR','EDGE','CB'],    s:['Kyler Murray','DeAndre Hopkins','Chandler Jones'],      w:'8-8' },
    ATL:{ n:['QB','WR','EDGE'],    s:['Calvin Ridley','A.J. Terrell'],                         w:'4-12' },
    BAL:{ n:['WR','EDGE','CB'],    s:['Lamar Jackson','Mark Andrews','Ronnie Stanley'],        w:'11-5' },
    BUF:{ n:['EDGE','WR','OT'],    s:['Josh Allen','Stefon Diggs','Tre White'],                w:'13-3' },
    CAR:{ n:['QB','WR','OT'],      s:['DJ Moore','Brian Burns'],                               w:'5-11' },
    CHI:{ n:['QB','WR','OT'],      s:['Khalil Mack','Allen Robinson','Akiem Hicks'],           w:'8-8' },
    CIN:{ n:['OT','WR','EDGE'],    s:['Joe Burrow','A.J. Green','Joe Mixon'],                  w:'4-11-1' },
    CLE:{ n:['WR','CB','EDGE'],    s:['Baker Mayfield','Nick Chubb','Jarvis Landry'],          w:'11-5' },
    DAL:{ n:['LB','CB','WR'],      s:['Dak Prescott','Ezekiel Elliott','CeeDee Lamb'],         w:'6-10' },
    DEN:{ n:['QB','WR','OT'],      s:['Von Miller','Courtland Sutton','Bradley Chubb'],        w:'5-11' },
    DET:{ n:['QB','WR','CB'],      s:['T.J. Hockenson'],                                       w:'5-11' },
    GB: { n:['WR','RB','EDGE'],    s:['Aaron Rodgers','Davante Adams',"Za'Darius Smith"],     w:'13-3' },
    HOU:{ n:['QB','WR','CB'],      s:['Brandin Cooks'],                                        w:'4-12' },
    IND:{ n:['QB','WR','CB'],      s:['Quenton Nelson','T.Y. Hilton','Darius Leonard'],        w:'11-5' },
    JAX:{ n:['QB','WR','OT'],      s:['DJ Chark','Josh Allen DE'],                             w:'1-15' },
    KC: { n:['OT','EDGE','CB'],    s:['Patrick Mahomes','Travis Kelce','Tyreek Hill'],         w:'14-2' },
    LAC:{ n:['OT','LB','WR'],      s:['Justin Herbert','Keenan Allen','Joey Bosa'],           w:'7-9' },
    LAR:{ n:['QB','CB','OT'],      s:['Aaron Donald','Cooper Kupp'],                           w:'10-6' },
    LV: { n:['WR','CB','OT'],      s:['Derek Carr','Hunter Renfrow','Maxx Crosby'],            w:'8-8' },
    MIA:{ n:['WR','OT','CB'],      s:['Tua Tagovailoa','DeVante Parker'],                      w:'10-6' },
    MIN:{ n:['CB','EDGE','OT'],    s:['Kirk Cousins','Justin Jefferson','Dalvin Cook'],        w:'7-9' },
    NE: { n:['QB','WR','EDGE'],    s:['Damien Harris',"Dont'a Hightower"],                    w:'7-9' },
    NO: { n:['QB','WR','CB'],      s:['Michael Thomas','Alvin Kamara'],                        w:'12-4' },
    NYG:{ n:['WR','OT','EDGE'],    s:['Daniel Jones'],                                         w:'6-10' },
    NYJ:{ n:['QB','OT','CB'],      s:['Corey Davis'],                                          w:'2-14' },
    PHI:{ n:['QB','WR','CB'],      s:['Jalen Hurts','Zach Ertz','Fletcher Cox'],              w:'4-11-1' },
    PIT:{ n:['WR','OT','CB'],      s:["Ben Roethlisberger (aging)","JuJu Smith-Schuster","TJ Watt"], w:'12-4' },
    SEA:{ n:['EDGE','OT','CB'],    s:['Russell Wilson','Tyler Lockett','DK Metcalf'],          w:'12-4' },
    SF: { n:['WR','EDGE','CB'],    s:['Jimmy Garoppolo','George Kittle','Deebo Samuel'],       w:'6-10' },
    TB: { n:['CB','OT','EDGE'],    s:['Tom Brady','Mike Evans','Rob Gronkowski'],              w:'11-5' },
    TEN:{ n:['WR','OT','CB'],      s:['Ryan Tannehill','Derrick Henry','AJ Brown'],            w:'11-5' },
    WAS:{ n:['QB','WR','OT'],      s:['Terry McLaurin','Chase Young','Landon Collins'],        w:'7-9' },
  },
  2022: {
    ARI:{ n:['CB','OT','EDGE'],    s:['Kyler Murray','DeAndre Hopkins'],                       w:'11-6' },
    ATL:{ n:['QB','WR','OT'],      s:['Kyle Pitts','Cordarrelle Patterson'],                   w:'7-10' },
    BAL:{ n:['WR','EDGE','CB'],    s:['Lamar Jackson','Mark Andrews','Ronnie Stanley'],        w:'8-9' },
    BUF:{ n:['CB','OT','S'],       s:['Josh Allen','Stefon Diggs','Von Miller'],               w:'11-6' },
    CAR:{ n:['QB','WR','OT'],      s:['Christian McCaffrey','DJ Moore','Brian Burns'],          w:'5-12' },
    CHI:{ n:['WR','OT','EDGE'],    s:['Justin Fields','Darnell Mooney','Roquan Smith'],        w:'6-11' },
    CIN:{ n:['OT','CB','EDGE'],    s:["Joe Burrow","Ja'Marr Chase","Tee Higgins"],             w:'10-7' },
    CLE:{ n:['QB','WR','CB'],      s:['Nick Chubb','Amari Cooper','Myles Garrett'],            w:'8-9' },
    DAL:{ n:['EDGE','OT','CB'],    s:['Dak Prescott','CeeDee Lamb','Micah Parsons'],           w:'12-5' },
    DEN:{ n:['QB','WR','OT'],      s:['Courtland Sutton','Patrick Surtain','Bradley Chubb'],   w:'7-10' },
    DET:{ n:['EDGE','CB','WR'],    s:['Penei Sewell','Amon-Ra St. Brown','Jared Goff'],       w:'3-13-1' },
    GB: { n:['WR','CB','OT'],      s:['Aaron Rodgers','Rashan Gary'],                          w:'13-4' },
    HOU:{ n:['QB','WR','OT'],      s:['Brandin Cooks'],                                        w:'4-13' },
    IND:{ n:['QB','WR','OT'],      s:['Quenton Nelson','Michael Pittman','Jonathan Taylor'],   w:'9-8' },
    JAX:{ n:['WR','CB','OT'],      s:['Trevor Lawrence','Travis Etienne'],                     w:'3-14' },
    KC: { n:['WR','EDGE','OT'],    s:['Patrick Mahomes','Travis Kelce'],                       w:'12-5' },
    LAC:{ n:['OT','LB','WR'],      s:['Justin Herbert','Keenan Allen','Joey Bosa'],           w:'9-8' },
    LAR:{ n:['CB','OT','WR'],      s:['Aaron Donald','Cooper Kupp','Matthew Stafford'],        w:'12-5' },
    LV: { n:['WR','CB','OT'],      s:['Derek Carr','Davante Adams','Maxx Crosby'],             w:'10-7' },
    MIA:{ n:['OT','EDGE','CB'],    s:['Tua Tagovailoa','Tyreek Hill','Jaylen Waddle'],         w:'9-8' },
    MIN:{ n:['CB','EDGE','OT'],    s:['Kirk Cousins','Justin Jefferson','Adam Thielen'],       w:'8-9' },
    NE: { n:['WR','EDGE','CB'],    s:['Mac Jones','Jakobi Meyers','Matthew Judon'],            w:'10-7' },
    NO: { n:['QB','WR','CB'],      s:['Alvin Kamara','Cameron Jordan'],                        w:'9-8' },
    NYG:{ n:['WR','OT','EDGE'],    s:['Daniel Jones','Saquon Barkley'],                        w:'4-13' },
    NYJ:{ n:['QB','WR','OT'],      s:['Garrett Wilson','Sauce Gardner','Zach Wilson'],          w:'4-13' },
    PHI:{ n:['WR','CB','OT'],      s:['Jalen Hurts','AJ Brown','Devonta Smith'],              w:'9-8' },
    PIT:{ n:['QB','WR','OT'],      s:['Diontae Johnson','TJ Watt','Najee Harris'],             w:'9-7-1' },
    SEA:{ n:['QB','CB','OT'],      s:['DK Metcalf','Tyler Lockett'],                           w:'7-10' },
    SF: { n:['CB','OT','EDGE'],    s:['Deebo Samuel','George Kittle','Nick Bosa'],             w:'10-7' },
    TB: { n:['WR','CB','OT'],      s:['Tom Brady','Mike Evans'],                               w:'13-4' },
    TEN:{ n:['WR','OT','CB'],      s:['Derrick Henry','Ryan Tannehill'],                       w:'12-5' },
    WAS:{ n:['QB','WR','OT'],      s:['Terry McLaurin','Chase Young','Antonio Gibson'],        w:'7-10' },
  },
  2023: {
    ARI:{ n:['QB','WR','OT'],      s:['Kyler Murray','DeAndre Hopkins'],                       w:'4-13' },
    ATL:{ n:['QB','WR','OT'],      s:['Kyle Pitts','Drake London','Grady Jarrett'],            w:'7-10' },
    BAL:{ n:['WR','OT','CB'],      s:['Lamar Jackson','Mark Andrews','Roquan Smith'],          w:'10-7' },
    BUF:{ n:['CB','EDGE','OT'],    s:['Josh Allen','Stefon Diggs','Von Miller'],               w:'13-3' },
    CAR:{ n:['QB','OT','CB'],      s:['DJ Moore (gone)','Brian Burns'],                        w:'7-10' },
    CHI:{ n:['WR','OT','CB'],      s:['Justin Fields','Darnell Mooney'],                       w:'3-14' },
    CIN:{ n:['OT','CB','EDGE'],    s:["Joe Burrow","Ja'Marr Chase","Tee Higgins"],             w:'12-4' },
    CLE:{ n:['QB','WR','OT'],      s:['Nick Chubb','Amari Cooper','Myles Garrett'],            w:'7-10' },
    DAL:{ n:['CB','WR','OT'],      s:['Dak Prescott','CeeDee Lamb','Micah Parsons'],           w:'12-5' },
    DEN:{ n:['QB','WR','OT'],      s:['Russell Wilson','Courtland Sutton','Patrick Surtain'],  w:'5-12' },
    DET:{ n:['EDGE','CB','WR'],    s:['Penei Sewell','Amon-Ra St. Brown','Jared Goff'],       w:'9-8' },
    GB: { n:['WR','CB','OT'],      s:['Jordan Love','Romeo Doubs','Rashan Gary'],              w:'8-9' },
    HOU:{ n:['QB','WR','CB'],      s:['Will Anderson'],                                         w:'3-13-1' },
    IND:{ n:['QB','WR','OT'],      s:['Michael Pittman','Jonathan Taylor'],                    w:'4-12-1' },
    JAX:{ n:['WR','CB','OT'],      s:['Trevor Lawrence','Travis Etienne','Evan Engram'],       w:'9-8' },
    KC: { n:['WR','EDGE','OT'],    s:['Patrick Mahomes','Travis Kelce','Chris Jones'],         w:'14-3' },
    LAC:{ n:['WR','OT','LB'],      s:['Justin Herbert','Keenan Allen','Joey Bosa'],           w:'10-7' },
    LAR:{ n:['EDGE','CB','OT'],    s:['Aaron Donald (retired)','Cooper Kupp'],                 w:'5-12' },
    LV: { n:['QB','WR','CB'],      s:['Davante Adams','Maxx Crosby'],                          w:'6-11' },
    MIA:{ n:['OT','EDGE','CB'],    s:['Tua Tagovailoa','Tyreek Hill','Jaylen Waddle'],         w:'9-8' },
    MIN:{ n:['QB','CB','EDGE'],    s:['Justin Jefferson','T.J. Hockenson'],                    w:'13-4' },
    NE: { n:['QB','WR','OT'],      s:['Rhamondre Stevenson','Matthew Judon'],                  w:'8-9' },
    NO: { n:['QB','WR','CB'],      s:['Michael Thomas','Alvin Kamara','Cameron Jordan'],       w:'7-10' },
    NYG:{ n:['WR','OT','EDGE'],    s:['Daniel Jones','Saquon Barkley'],                        w:'9-7-1' },
    NYJ:{ n:['QB','WR','OT'],      s:['Aaron Rodgers','Garrett Wilson','Sauce Gardner'],        w:'7-10' },
    PHI:{ n:['CB','EDGE','WR'],    s:['Jalen Hurts','AJ Brown','Devonta Smith'],              w:'14-3' },
    PIT:{ n:['QB','WR','OT'],      s:['Kenny Pickett','Diontae Johnson','TJ Watt'],            w:'9-8' },
    SEA:{ n:['QB','OT','CB'],      s:['DK Metcalf','Tyler Lockett','Geno Smith'],              w:'9-8' },
    SF: { n:['CB','OT','EDGE'],    s:['Christian McCaffrey','George Kittle','Nick Bosa'],      w:'13-4' },
    TB: { n:['QB','WR','OT'],      s:['Mike Evans','Chris Godwin','Lavonte David'],            w:'8-9' },
    TEN:{ n:['QB','WR','OT'],      s:['Treylon Burks','Derrick Henry','Harold Landry'],        w:'7-10' },
    WAS:{ n:['QB','WR','OT'],      s:['Terry McLaurin','Chase Young','Sam Howell'],            w:'8-8-1' },
  },
  2024: {
    ARI:{ n:['OT','CB','EDGE'],    s:['Kyler Murray','Marvin Harrison Jr','Zaven Collins'],    w:'4-13' },
    ATL:{ n:['QB','WR','OT'],      s:['Bijan Robinson','Drake London','Kyle Pitts'],           w:'7-10' },
    BAL:{ n:['WR','OT','CB'],      s:['Lamar Jackson','Mark Andrews','Roquan Smith'],          w:'13-4' },
    BUF:{ n:['CB','WR','OT'],      s:['Josh Allen','Von Miller'],                              w:'11-6' },
    CAR:{ n:['OT','WR','EDGE'],    s:['Bryce Young','Diontae Johnson'],                        w:'2-15' },
    CHI:{ n:['WR','OT','CB'],      s:['DJ Moore','Rome Odunze'],                               w:'7-10' },
    CIN:{ n:['OT','CB','EDGE'],    s:["Joe Burrow","Ja'Marr Chase","Tee Higgins"],             w:'9-8' },
    CLE:{ n:['QB','WR','OT'],      s:['Nick Chubb','Jerry Jeudy','Myles Garrett'],             w:'11-6' },
    DAL:{ n:['OT','WR','CB'],      s:['Dak Prescott','CeeDee Lamb','Micah Parsons'],           w:'12-5' },
    DEN:{ n:['QB','WR','OT'],      s:['Courtland Sutton','Patrick Surtain'],                   w:'8-9' },
    DET:{ n:['CB','EDGE','WR'],    s:['Jared Goff','Amon-Ra St. Brown','Sam LaPorta'],        w:'12-5' },
    GB: { n:['WR','CB','OT'],      s:['Jordan Love','Romeo Doubs','Christian Watson'],        w:'9-8' },
    HOU:{ n:['WR','OT','CB'],      s:['CJ Stroud','Nico Collins','Will Anderson'],             w:'10-7' },
    IND:{ n:['WR','OT','CB'],      s:['Anthony Richardson','Michael Pittman','Jonathan Taylor'],w:'10-7' },
    JAX:{ n:['WR','CB','OT'],      s:['Trevor Lawrence','Travis Etienne'],                     w:'9-8' },
    KC: { n:['WR','EDGE','OT'],    s:['Patrick Mahomes','Travis Kelce','Chris Jones'],         w:'11-6' },
    LAC:{ n:['WR','OT','EDGE'],    s:['Justin Herbert','Joey Bosa'],                           w:'5-12' },
    LAR:{ n:['CB','OT','EDGE'],    s:['Cooper Kupp','Puka Nacua'],                             w:'10-7' },
    LV: { n:['QB','WR','CB'],      s:['Brock Bowers','Maxx Crosby','Davante Adams'],           w:'8-9' },
    MIA:{ n:['OT','EDGE','CB'],    s:['Tua Tagovailoa','Tyreek Hill','Jaylen Waddle'],         w:'11-6' },
    MIN:{ n:['QB','CB','OT'],      s:['Justin Jefferson','T.J. Hockenson','Jordan Addison'],   w:'7-10' },
    NE: { n:['QB','WR','OT'],      s:['Kendrick Bourne','Christian Barmore'],                  w:'4-13' },
    NO: { n:['QB','WR','OT'],      s:['Derek Carr','Chris Olave','Alvin Kamara'],             w:'9-8' },
    NYG:{ n:['QB','WR','OT'],      s:['Saquon Barkley (gone)'],                                w:'6-11' },
    NYJ:{ n:['WR','CB','OT'],      s:['Aaron Rodgers','Garrett Wilson','Sauce Gardner'],        w:'7-10' },
    PHI:{ n:['CB','EDGE','WR'],    s:['Jalen Hurts','AJ Brown','Devonta Smith'],              w:'11-6' },
    PIT:{ n:['QB','WR','OT'],      s:['Najee Harris','TJ Watt','Pat Freiermuth'],              w:'10-7' },
    SEA:{ n:['QB','OT','CB'],      s:['DK Metcalf','Tyler Lockett','Geno Smith'],              w:'9-8' },
    SF: { n:['CB','OT','EDGE'],    s:['Christian McCaffrey','George Kittle','Deebo Samuel'],   w:'12-5' },
    TB: { n:['WR','CB','OT'],      s:['Baker Mayfield','Mike Evans','Chris Godwin'],           w:'9-8' },
    TEN:{ n:['QB','RB','OT'],      s:['Treylon Burks','Harold Landry'],                        w:'6-11' },
    WAS:{ n:['OT','CB','WR'],      s:['Terry McLaurin','Jonathan Allen'],                      w:'4-13' },
  },
  2025: {
    ARI:{ n:['CB','EDGE','OT'],    s:['Kyler Murray','Marvin Harrison Jr.','James Conner'],    w:'8-9' },
    ATL:{ n:['OT','CB','EDGE'],    s:['Michael Penix Jr.','Drake London','Kyle Pitts'],        w:'8-9' },
    BAL:{ n:['WR','OT','CB'],      s:['Lamar Jackson','Mark Andrews'],                         w:'12-5' },
    BUF:{ n:['WR','CB','OT'],      s:['Josh Allen','Amari Cooper','Dalton Kincaid'],           w:'13-4' },
    CAR:{ n:['OT','WR','CB'],      s:['Bryce Young','Diontae Johnson'],                        w:'5-12' },
    CHI:{ n:['WR','OT','CB'],      s:['Caleb Williams','Rome Odunze','DJ Moore'],              w:'5-12' },
    CIN:{ n:['OT','CB','EDGE'],    s:["Joe Burrow","Ja'Marr Chase"],                           w:'9-8' },
    CLE:{ n:['QB','WR','OT'],      s:['Myles Garrett','Jerry Jeudy'],                          w:'3-14' },
    DAL:{ n:['OT','WR','CB'],      s:['CeeDee Lamb','Micah Parsons','Dak Prescott'],           w:'7-10' },
    DEN:{ n:['WR','OT','CB'],      s:['Bo Nix','Courtland Sutton','Patrick Surtain'],          w:'10-7' },
    DET:{ n:['CB','EDGE','WR'],    s:['Jared Goff','Amon-Ra St. Brown','Jahmyr Gibbs'],       w:'15-2' },
    GB: { n:['WR','CB','OT'],      s:['Jordan Love','Jayden Reed','Josh Jacobs'],              w:'11-6' },
    HOU:{ n:['WR','OT','CB'],      s:['CJ Stroud','Nico Collins','Will Anderson'],             w:'10-7' },
    IND:{ n:['WR','OT','CB'],      s:['Anthony Richardson','Michael Pittman','Quenton Nelson'], w:'8-9' },
    JAX:{ n:['WR','CB','OT'],      s:['Trevor Lawrence','Travis Etienne','Evan Engram'],       w:'4-13' },
    KC: { n:['WR','EDGE','OT'],    s:['Patrick Mahomes','Travis Kelce','Chris Jones'],         w:'15-2' },
    LAC:{ n:['WR','OT','LB'],      s:['Justin Herbert','Ladd McConkey'],                       w:'11-6' },
    LAR:{ n:['CB','OT','EDGE'],    s:['Matthew Stafford','Cooper Kupp'],                       w:'10-7' },
    LV: { n:['QB','WR','RB'],      s:['Brock Bowers','Maxx Crosby'],                          w:'4-13' },
    MIA:{ n:['OT','EDGE','CB'],    s:['Tua Tagovailoa','Tyreek Hill','Jaylen Waddle'],         w:'8-9' },
    MIN:{ n:['WR','CB','EDGE'],    s:['Justin Jefferson','Jordan Addison'],                    w:'14-3' },
    NE: { n:['WR','OT','EDGE'],    s:['Drake Maye','Kendrick Bourne','Christian Barmore'],     w:'4-13' },
    NO: { n:['QB','WR','OT'],      s:['Chris Olave','Alvin Kamara','Cameron Jordan'],          w:'5-12' },
    NYG:{ n:['QB','OT','WR'],      s:['Brian Burns','Malik Nabers','Devin Singletary'],        w:'3-14' },
    NYJ:{ n:['QB','WR','OT'],      s:['Garrett Wilson','Sauce Gardner','Breece Hall'],         w:'5-12' },
    PHI:{ n:['CB','EDGE','OT'],    s:['Jalen Hurts','AJ Brown','Saquon Barkley'],              w:'14-3' },
    PIT:{ n:['QB','WR','OT'],      s:['TJ Watt','Najee Harris','George Pickens'],              w:'10-7' },
    SEA:{ n:['QB','OT','CB'],      s:['DK Metcalf','Tyler Lockett','Geno Smith'],              w:'10-7' },
    SF: { n:['OT','CB','EDGE'],    s:['Brock Purdy','George Kittle','Deebo Samuel'],           w:'6-11' },
    TB: { n:['WR','CB','OT'],      s:['Baker Mayfield','Mike Evans'],                          w:'10-7' },
    TEN:{ n:['QB','OT','WR'],      s:['Will Levis','Calvin Ridley','Harold Landry'],           w:'3-14' },
    WAS:{ n:['OT','CB','WR'],      s:['Jayden Daniels','Terry McLaurin','Brian Robinson Jr.'], w:'12-5' },
  },
};